add experiment error message popover
arayabrain/optinist-for-server pull request #106
Opened 2023-08-07 14:49 UTC by ReiHashimoto

Result欄にエラーメッセージを表示するpopoverを追加
エラーが発生したノードのエラーアイコンクリックで表示

![Screenshot 2023-08-07 at 23 41 04](https://github.com/arayabrain/optinist-for-server/assets/42664619/f5043224-4143-491f-aa65-759418c7af87)

2023-08-08 07:23 UTC, itutu-tienday requested changes
@ReiHashimoto 
何点かレビューコメントを記載しています。ご確認ください。

2023-08-08 07:23 UTC, itutu-tienday commented on frontend/src/components/Workspace/Experiment/CollapsibleTable.tsx
>      <TableRow key={nodeId}>
レコードのツリーを展開した際、以下 FEコンソール上のエラーが発生するようです。

```
index.js:1  Warning: Each child in a list should have a unique "key" prop. See https://reactjs.org/link/warning-keys for more information.
    at http://localhost:3000/static/js/main.chunk.js:7890:5
    at http://localhost:3000/static/js/main.chunk.js:7867:60
    at table
～～ 以下略 ～～
```

上記のエラー発生後は、画面がそれ以上下へスクロールしなくなる（見切れる）ようです。

2023-08-08 07:23 UTC, itutu-tienday commented on frontend/src/components/Workspace/Experiment/CollapsibleTable.tsx
> +          <Typography sx={{ p: 2 }}>{message}</Typography>
エラーメッセージは、赤系（crimsonなど）で表示するとよいかと思います。

2023-08-08 09:15 UTC, ReiHashimoto commented on frontend/src/components/Workspace/Experiment/CollapsibleTable.tsx
> +          <Typography sx={{ p: 2 }}>{message}</Typography>
メッセージのcolor、fontSize, paddingなどを調整しました

2023-08-08 09:17 UTC, ReiHashimoto commented on frontend/src/components/Workspace/Experiment/CollapsibleTable.tsx
>      <TableRow key={nodeId}>
mapなどで展開するli系の要素にkeyが含まれていない箇所が今回の実装以外で多数あるのが原因のようです。この件は別途対応としましょう。

画面のスクロールについてですが、mainタグのheightがロード時点での100vhで固定になっていたのが原因のため、除去して可変にしました。
frontend/src/components/Workspace/Experiment/Experiment.tsx

2023-08-09 03:45 UTC, itutu-tienday approved these changes

2023-08-09 03:45 UTC, merged