inputディレクトリをworkspace idで分離
arayabrain/optinist-for-server pull request #119
Opened 2023-08-10 09:17 UTC by ReiHashimoto

- inputのディレクトリを`input/{workspace_id}/`で分離
- `output/` apiでinputディレクトリの参照にも使用されるもの(`output/csv`, `output/image`)および`/hdf5`のapiについては、クエリパラメータとしてworkspace_idを必須として対応
  - パスパラメータでも良いが、他のouput apiと体裁を整えるためこのような実装としている

2023-08-17 08:20 UTC, itutu-tienday requested changes

2023-08-17 08:20 UTC, itutu-tienday commented on studio/app/common/routers/files.py
>              os.listdir(absolute_dirpath),
@ReiHashimoto 
細かい指摘ですが、ここで対象ディレクトリパスが存在しない（まだ一度もファイルをアップロードしていない）場合、例外となっているようです。
例外処理 or パスの存在チェックを入れておくとよいと思います。

2023-08-17 08:55 UTC, ReiHashimoto commented on studio/app/common/routers/files.py
>              os.listdir(absolute_dirpath),
@itutu-tienday 
指摘ありがとうございます！
エラーハンドリングを追加しました。

2023-08-17 09:24 UTC, itutu-tienday requested changes
@ReiHashimoto 
一点確認ですが、STANDALONEモードでデータをアップロードした場合、データフォルダは「input/1」となるようです。
「input/default」となるように想定していましたが、上記は想定通りのフォルダ構成でしょうか？

2023-08-17 11:20 UTC, ReiHashimoto commented
@itutu-tienday 
- frontendがworkspace_idを基本的にnumberで持つようになったので、#89 のPRの際にdefault→1に変えました

2023-08-18 05:05 UTC, itutu-tienday approved these changes

2023-08-18 06:11 UTC, merged