account profile page
arayabrain/optinist-for-server pull request #122
Opened 2023-08-10 13:27 UTC by sanglevinh

2023-08-10 23:10 UTC, itutu-tienday requested changes

2023-08-10 23:10 UTC, itutu-tienday commented on frontend/src/pages/Dashboard/index.tsx
> +          <LinkWrapper to="/console/account">
@sanglevinh 
The following commit removes the link to Account Profile from the Dashboard screen. (This is also reflected in the latest screen design document)
https://github.com/arayabrain/optinist-for-server/commit/bd1bb9bd3c94f4be286f2976317aeaa0a9cf1901#diff-bfab1356838500bce166e376140 b1c5c145f576b6fd64dbc9f2d1d322ea4931d

Due to the above, please remove the link on the Dashboard screen.

2023-08-10 23:10 UTC, itutu-tienday commented on frontend/src/pages/Dashboard/index.tsx
>                  <AccountCircleIcon fontSize="large" />
@sanglevinh 
It may have already been pointed out, but is the pagenation query parameter given to the link to each screen where the DataGrid is located, or is this mandatory?
(If it is optional, I would like to remove the link parameter, for example by using the default value. (Considering it will be bookmarked, etc.))

2023-08-11 00:13 UTC, itutu-tienday requested changes

2023-08-11 00:13 UTC, itutu-tienday commented on frontend/src/pages/Account/index.tsx
> +        {isEditName ? (
@sanglevinh 
Input fields should be able to be confirmed with the Enter key and canceled with the Esc key.

2023-08-11 00:13 UTC, itutu-tienday commented on frontend/src/pages/Account/index.tsx
> +        <BoxData>{user?.id}</BoxData>
Please show uid here.

2023-08-11 00:13 UTC, itutu-tienday commented on frontend/src/pages/Account/index.tsx
> +        <BoxData>{user?.organization_id}</BoxData>
Please show organization_name here.

2023-08-11 08:54 UTC, sanglevinh commented on frontend/src/pages/Dashboard/index.tsx
> +          <LinkWrapper to="/console/account">
@itutu-tienday i deleted it

2023-08-11 09:58 UTC, sanglevinh commented on frontend/src/pages/Account/index.tsx
> +        {isEditName ? (
@itutu-tienday i deleted it

2023-08-11 09:59 UTC, sanglevinh commented on frontend/src/pages/Dashboard/index.tsx
>                  <AccountCircleIcon fontSize="large" />
@itutu-tienday i deleted it

2023-08-11 10:35 UTC, sanglevinh commented on frontend/src/pages/Account/index.tsx
> +        <BoxData>{user?.id}</BoxData>
@itutu-tienday i added it

2023-08-11 10:36 UTC, sanglevinh commented on frontend/src/pages/Account/index.tsx
> +        <BoxData>{user?.organization_id}</BoxData>
@itutu-tienday i fiexd it

2023-08-11 13:46 UTC, itutu-tienday approved these changes

2023-08-15 01:43 UTC, ReiHashimoto requested changes

2023-08-15 01:43 UTC, ReiHashimoto commented on frontend/src/components/PopupShare.tsx
> +import {DataGrid, GridRenderCellParams, GridValidRowModel} from "@mui/x-data-grid";
I found following error on yarn start.

```
TypeScript error in /Users/rei_hashimoto/GitHub/review.optinist-for-server/frontend/src/components/PopupShare.tsx(5,41):
Module '"@mui/x-data-grid"' has no exported member 'GridValidRowModel'.  TS2305
```

Could you check if it reproduce on your env?

2023-08-15 02:47 UTC, sanglevinh commented on frontend/src/components/PopupShare.tsx
> +import {DataGrid, GridRenderCellParams, GridValidRowModel} from "@mui/x-data-grid";
@ReiHashimoto I fixed it, please check again

2023-08-15 04:33 UTC, ReiHashimoto approved these changes
LGTM

2023-08-15 04:34 UTC, merged