Feature/update database and workspace and Esc close popup (Database)
arayabrain/optinist-for-server pull request #124
Opened 2023-08-11 12:30 UTC by sanglevinh

2023-08-11 14:16 UTC, itutu-tienday requested changes

2023-08-11 14:16 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                {
@sanglevinh 

When I operate publish(on/off) with the DataGrid filter enabled, the following condition seems to occur.
- The filter remains enabled in the UI, but the filter is not actually functioning (all data is re-searched).

Please adjust the above as follows.
- When the list is reacquired after the "publish(on/off)" operation, if the filter exists, the search is performed using the filter.
- \* If this is difficult to handle, please contact us.

2023-08-14 04:47 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                {
@itutu-tienday I fixed it, can you please check it again

2023-08-17 00:28 UTC, itutu-tienday approved these changes

2023-08-17 00:57 UTC, merged