navigate login when expried
arayabrain/optinist-for-server pull request #130
Opened 2023-08-18 11:36 UTC by sanglevinh

2023-08-21 03:45 UTC, itutu-tienday requested changes

2023-08-21 03:45 UTC, itutu-tienday commented on frontend/src/utils/axios.ts
> +    if (error?.response?.status === 400) {
@sanglevinh 
With this modification, will it also transition to the login screen when a 400 error other than auth API occurs?
-> We would like to have an automatic transition to the SignIn screen only when a SignOut is detected.

Also, if a screen transition is made in the SignOut state (to the Dashboard, etc.), we expect the screen to transition to the SingIn screen.

2023-08-21 07:12 UTC, sanglevinh commented on frontend/src/utils/axios.ts
> +    if (error?.response?.status === 400) {
@itutu-tienday i fixed it, please check it again

2023-08-22 06:26 UTC, itutu-tienday approved these changes

2023-08-22 22:47 UTC, merged