fix width table datagrid
arayabrain/optinist-for-server pull request #133
Opened 2023-08-21 09:17 UTC by sanglevinh

2023-08-21 11:13 UTC, ReiHashimoto requested changes

2023-08-21 11:13 UTC, ReiHashimoto commented on frontend/src/pages/Workspace/index.tsx
> +    minWidth: 100,
could you fix this and records's minWidth to a bit wider?
- because some button's styles were changed in #131 .
- please rebase this branch to the latest develop-main, too.

2023-08-21 11:13 UTC, ReiHashimoto commented on frontend/src/pages/Workspace/index.tsx
> +    minWidth: 100,
Do you have any solutions to the problem of the edit button being hidden when the name is long?
![Screenshot 2023-08-21 at 20 08 41](https://github.com/arayabrain/optinist-for-server/assets/42664619/21547641-eeeb-44a6-bb0e-cc487a25b616)

2023-08-22 03:18 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +    minWidth: 100,
@ReiHashimoto i changed minWidth to 160, do you think that makes sense?

2023-08-22 03:20 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +    minWidth: 100,
@ReiHashimoto when the name is too long, i'll set it as '...' and add a tooltip to show its name, okay?

2023-08-22 04:45 UTC, ReiHashimoto commented on frontend/src/pages/Workspace/index.tsx
> +    minWidth: 100,
@sanglevinh Looks fine. Thank you!

2023-08-22 04:46 UTC, ReiHashimoto approved these changes

2023-08-22 07:01 UTC, merged