integrate api cancel
arayabrain/optinist-for-server pull request #136
Opened 2023-08-29 04:03 UTC by sanglevinh

2023-08-29 04:57 UTC, itutu-tienday requested changes
@sanglevinh 
Please check the indicated items.

2023-08-29 04:57 UTC, itutu-tienday commented on frontend/src/api/run/Run.ts
> +export async function cancelResultApi(data: {
If the workflow is not RUN, please leave the Cancel button disabled.
* If there are any implementation problems, please let me know.

2023-08-29 04:57 UTC, itutu-tienday commented on frontend/src/store/slice/Pipeline/PipelineActions.ts
> +      const responseData = await cancelResultApi({
Please display the message (snackbar) when the process is done.

- Messages
  - On success (code 200):  "Workflow stopped."
  - On error (except code 200): "Failed to stop workflow. Please try again."

2023-08-29 08:16 UTC, sanglevinh commented on frontend/src/store/slice/Pipeline/PipelineActions.ts
> +      const responseData = await cancelResultApi({
@itutu-tienday  i added it, please check again

2023-08-29 08:16 UTC, sanglevinh commented on frontend/src/api/run/Run.ts
> +export async function cancelResultApi(data: {
@itutu-tienday i fixed it, please check again

2023-08-29 09:11 UTC, itutu-tienday requested changes

2023-08-29 10:23 UTC, sanglevinh commented on frontend/src/api/run/Run.ts
> +export async function cancelResultApi(data: {
@itutu-tienday I have used it, can you check if it aligns with your intention?

2023-08-30 01:54 UTC, itutu-tienday requested changes

2023-08-30 01:54 UTC, itutu-tienday commented on frontend/src/api/run/Run.ts
> +export async function cancelResultApi(data: {
@sanglevinh 
I have checked the operation and it appears to be working as expected.
Are there any concerns in the code as well? If there are no particular concerns, I will approve this fix.

2023-08-30 02:13 UTC, sanglevinh commented on frontend/src/api/run/Run.ts
> +export async function cancelResultApi(data: {
@itutu-tienday I don't see any problem at the moment, if there is, I will fix it later

2023-08-31 02:27 UTC, itutu-tienday approved these changes

2023-08-31 04:24 UTC, merged