add expdb batch
arayabrain/optinist-for-server pull request #145
Opened 2023-09-05 00:20 UTC by ReiHashimoto

- エントリポイント run_batchから起動
    ```
    python run_batch.py -o 1
    ```
  - 組織IDは実行時指定ではなく事前に定数などでの定義も検討

2023-09-05 07:28 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_runner.py
> +        with Session(engine) as db:
以下のDB操作処理では、各メソッド（cleanup_*, create_*）内で逐次 commit しているように見えますが、
一定の区間でトランザクションを張るのがよい様に思います。
※少なくとも、 create_experiment と  bulk_insert_cells はセットにしておく必要があると思われる。

2023-09-05 07:28 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_unit.py
> +        try:
他の experiments 関連テーブルも、削除しておくのがよい思われます。
- experiments_share_users

2023-09-05 07:28 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_runner.py
> +            expdb_batch.generate_statdata()
（動作確認の中で気づきましたが、）
各出力データは、EXPERIMENT_IDディレクトリの配下に "output" などのディレクトリを1つ挟んで出力する形が、保守性がよいものと思います。
→ お手数ですが、上記調整いただければと思います。

2023-09-05 07:28 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_runner.py
> +                "complete_time": datetime.datetime.now(),
complete_time と合わせて、start_time も記録いただければと思います。

2023-09-05 07:28 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_runner.py
> +            exp = asyncio.run(
これは質問ですが、
各DBアクセス処理を非同期形式（asyncio利用）としている事由を、確認させてください。

2023-09-05 07:28 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_runner.py
> +            expdb_batch.generate_statdata()
ここで生成された各種ファイルデータは、最終的に公開サイトのdocroot配下への転送が必要ですが、その処理は想定されていますでしょうか？

2023-09-05 07:28 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/crud_cells.py
> +        for cell in range(cells):
cells は多数（1,000件以上）の登録が想定されるため、ここはメソッド名の通り、bulk insert 形式で実施する形が望ましいと思います。 
（処理速度の他、ログが多数のinsert文で流れてしまう点を考慮）

※以下の機能などでしょうか
https://docs.sqlalchemy.org/en/20/orm/queryguide/dml.html#orm-bulk-insert-statements

2023-09-05 23:43 UTC, itutu-tienday requested changes

2023-09-05 23:43 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/crud_cells.py
> +        raise HTTPException(status_code=404, detail=str(e))
ここで例外にHTTPExceptionを利用する形は、必要でしたでしょうか？
※例外発生時にログにHTTPExceptionが記録されていたため、通信エラーが生じているのか、やや見分けづらかったため、必須でなければ、他の例外クラスに差し替えてもよいかもしれません。

2023-09-06 05:51 UTC, ReiHashimoto commented on studio/app/optinist/models/expdb/cell.py
> +    sequence: int = Field(
ありがとうございます。
cell_numberで対応しようかと思いますが、いかがでしょうか?
（cell_noでも良いですが、気になるほどの長さでもないかなと思い）

2023-09-06 06:03 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_runner.py
> +            exp = asyncio.run(
crud_usesの実装に合わせただけなので、明示的に理由があるわけではないです。
むしろそれらも含め、同期処理にした方が扱いやすそうですね。

2023-09-06 06:04 UTC, itutu-tienday commented on studio/app/optinist/models/expdb/cell.py
> +    sequence: int = Field(
@ReiHashimoto 
上記、名称OKと思います。

2023-09-06 06:05 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_runner.py
> +            exp = asyncio.run(
@ReiHashimoto 
了解しました。
もし修正による影響があまりないようであれば、シンプル（）

2023-09-06 07:33 UTC, itutu-tienday requested changes

2023-09-06 07:33 UTC, itutu-tienday commented on run_batch.py
> +import argparse
細かな指摘ですが、
このファイルのファイル名は、 run_batch.py → run_expdb_batch.py あたりが適当そうかと思います。

2023-09-06 13:37 UTC, ReiHashimoto commented on run_batch.py
> +import argparse
ファイル名をrun_expdb_batch.pyに修正しました。

2023-09-06 13:40 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/crud_cells.py
> +        raise HTTPException(status_code=404, detail=str(e))
APIから利用するケース想定でのExceptionでしたが、そもそもcrud処理単体ではHTTPExceptionは不適切ですね。
また、エラーハンドリングが冗長だったため、session_scopeで捕捉させるように統一しました。

crud_usersなども別途修正必要そうです。

2023-09-06 13:54 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/crud_cells.py
> +        for cell in range(cells):
sqlalchemy.coreのbulk_insertに修正しました。

https://docs.sqlalchemy.org/en/13/faq/performance.html#i-m-inserting-400-000-rows-with-the-orm-and-it-s-really-slow

また、上記のFAQのテスト内容(`test_sqlalchemy_core`)にあるように、sqlalchemy.coreの場合は10万件レベルでもchunkに分割もしていないようで、一旦分割なしで実装してみました。

2023-09-06 13:55 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_runner.py
> +            expdb_batch.generate_statdata()
.envでPUBLIC_EXPDB_DIRを追加で指定し、こちらにも保存するように修正しました。

2023-09-06 13:56 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_runner.py
> +            exp = asyncio.run(
同期処理に修正しました。
この処理に限らず、非同期処理はうまく使えるところは使っていきたいですね。

2023-09-06 13:57 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_runner.py
> +            expdb_batch.generate_statdata()
outputsディレクトリを挟むようにしました。

2023-09-06 13:57 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_unit.py
> +        try:
考慮漏れていました、ありがとうございます。
こちらのexperimentsの削除時にこちらも削除されるように修正しました。

2023-09-06 14:00 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_runner.py
> +        with Session(engine) as db:
crud_cells, crud_expdbではcommitせず、contextmanagerのsession_scopeでwrapしてsession終了時にcommitするようにしました。

なお、__process_dataset_registrationのcleanup_exp_recordの際には一度明示的にcommitを入れています。
※画像ファイルの削除が伴い、レコードの削除も確定させたいため。

2023-09-07 06:07 UTC, itutu-tienday commented on studio/app/optinist/models/expdb/cell.py
> +    sequence: int = Field(
@ReiHashimoto 
以下のファイルに "sequence" のキーワードが残っている様なのですが、問題ありませんでしょうか？（そのため  alembic upgrade head でエラーになる模様？）

- `alembic/versions/5f4f7615e37e_add_sequence_to_cells.py`

2023-09-07 06:22 UTC, ReiHashimoto commented on studio/app/optinist/models/expdb/cell.py
> +    sequence: int = Field(
`alembic/versions/206c32e0128b_rename_sequence_to_cell_number.py`
がその後のupdateになるので、sequenceが残っていること自体は問題ないはずです。

一度cellsをクリーンにしていただく必要があります。
cell_numberのunique_constraintで、experiment_uid と cell_numberの組み合わせでユニークになる制約を入れており、カラムの追加の際に連番が振られないので制約に反してしまうのが原因と思われます。

制約外しますか?

2023-09-07 06:24 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/crud_cells.py
> +        for cell in range(cells):
修正確認しました。

※SQLログの出力も、以下の様に適度に省略されており、ログ的に良い感じですね。
> ... displaying 10 of 136 total bound parameter sets ...

2023-09-07 06:37 UTC, itutu-tienday commented on studio/app/optinist/models/expdb/cell.py
> +    sequence: int = Field(
@ReiHashimoto 
update がうまくいかないところ、直接 alter table で調整したためか、cellsのレコードをdeleteしても、以下など処理が通らなくなっているようです。。

> sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1060, "Duplicate column name 'sequence'")
> [SQL: ALTER TABLE cells ADD COLUMN sequence INTEGER NOT NULL COMMENT 'sequence number of cell in experiment']

とりあえず上記は今少し確認して解消しようと思いますが、
運用時の `alembic upgrade head` は注意が必要ですね。（データの消失がない様に）

2023-09-07 06:43 UTC, ReiHashimoto commented on studio/app/optinist/models/expdb/cell.py
> +    sequence: int = Field(
@itutu-tienday 
sequenceの生成が絡むmigrationを削ること自体はあまり負荷なく対応可能ですので、うまく回らないようであればお申し付けください！

migration時にdummyでも連番降るなどできないかも追って調査します。

2023-09-07 06:47 UTC, itutu-tienday commented on studio/app/optinist/models/expdb/cell.py
> +    sequence: int = Field(
了解しました。
とりあえず sequence → cell_number への直接renameでバッチは動作しているので、一旦このissueはクローズします。

2023-09-07 06:56 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_runner.py
> +            expdb_batch.generate_statdata()
@ReiHashimoto 
以下、幾つか記載します

- 要望
  - 公開ディレクトリでは、"output" フォルダは作成不要でよいかと思います。
    - → 公開ディレクトリ（外部に公開するURL）は、なるべくコンパクトな形がよいと考えますが、対応が容易そうであれば、対応をいただければと思います。

- 質問
  - （動作未確認なのですが、）PUBLIC_EXPDB_DIR が以下のケースの場合、どのような動作になりますでしょうか？
    1. PUBLIC_EXPDB_DIR が未定義（設定ミス）
    2. PUBLIC_EXPDB_DIR と EXPDB_DIR が同じパス（設定ミス）

2023-09-07 07:37 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_runner.py
> +            expdb_batch.generate_statdata()
@itutu-tienday 

> PUBLIC_EXPDB_DIR が以下のケースの場合

- PUBLIC_EXPDB_DIR が未定義 -> OUTPUT_DIRが割り当たります
- PUBLIC_EXPDB_DIR と EXPDB_DIR が同じパス
  - EXPDB_DIRが正の場合
    - batch処理のステータス自体は正常終了
      - datasetのoutputsディレクトリに2回書き込みが発生し、本来publicにしたいディレクトリにはファイルが生成されない
  - PUBLIC_EXPDB_DIRが正の場合
    - 対象experimentのバッチが初回であれば、以下の部分でException
      ```python
      class ExpDbBatch:
        def __init__(self, exp_id: str, org_id: int) -> None:
            self.logger_ = logging.getLogger()
            self.exp_id = exp_id
            self.org_id = org_id
    
            self.raw_path = ExpDbPath(self.exp_id, is_raw=True)
            if not (os.path.exists(self.raw_path.exp_dir)):
                raise Exception(
                    f"Experiment directory for id: {self.exp_id} does not exist"
                )
      ```
  - 実行済みのexperimentのバッチ再実行(かつ、前回の実行前後で環境変数が変わってしまっている場合)
    - publicディレクトリのoutputs以下、およびDBのレコードは消される
    - 以下の部分でmatファイルのロードの際にException
      ```python
      def generate_statdata(self):
        expdb = ExpDbData(paths=[self.raw_path.tc_file, self.raw_path.ts_file])
      ```

> 公開ディレクトリでは、"output" フォルダは作成不要

- 確かに不要ではありますが、上記の設定ミス想定を踏まえると、outputの一つ上の階層を消し込む処理がrawデータを消す可能性が出てくるのが不安ではありますね。
- ひとまず、
  - PUBLIC_EXPDB_DIR が未定義 / PUBLIC_EXPDB_DIR と EXPDB_DIR が同じパス -> アプリ起動時点でExceptionとしてエラー終了 のバリデーションは入れましょうか。
  - 起動時点でのデータ存在確認でのバリデーションは、必ず存在するexperiment_idが必要になってくるかと思います。

2023-09-07 08:16 UTC, itutu-tienday approved these changes

2023-09-07 10:50 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_runner.py
> +            expdb_batch.generate_statdata()
@itutu-tienday 
EXPDB_DIR, PUBLIX_DIRの.envへの記載・ディレクトリの存在チェックのバリデーションを追加しました。

また、公開ディレクトリからoutputディレクトリを無くす代わりに、tc_fileやts_fileの存在確認を早期（各種消し込みを行う前）で行うようにしました。

2023-09-07 10:51 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_runner.py
> +            expdb_batch.generate_statdata()
なお、organization_idのバリデーションも追加済みです。

2023-09-07 11:01 UTC, merged