merge barebone-studio updates
arayabrain/optinist-for-server pull request #148
Opened 2023-09-05 07:48 UTC by ReiHashimoto

2023-09-06 06:02 UTC, itutu-tienday requested changes

2023-09-06 06:02 UTC, itutu-tienday commented on studio/__main_unit__.py
> -@app.get("/{_:path}")
@ReiHashimoto 
一旦の共有ですが、以下など、for serverで対応した必要機能（まだbare-boneへ反映していないもの）が、落ちている箇所があるようです。
→ 精査が必要ですが、一旦は可能な範囲で、動作確認を行っておいていただければと思います。

※当PRは修正ファイル数が一定 多いため、反映とテストのタイミングを、要判断かと思います。 （リリース当初は、最低限必要な修正（OPTINIST_DIR配下の変更）の反映のみとする、等）
→ 直近に相談をお願いします。

2023-09-06 06:08 UTC, ReiHashimoto commented on studio/__main_unit__.py
> -@app.get("/{_:path}")
確かに抜けていますね...
conflictなしで削れてしまう部分はbareboneが優先されてしまうので要精査ですね、ありがとうございます。

2023-09-06 06:50 UTC, itutu-tienday commented on studio/__main_unit__.py
> -@app.get("/{_:path}")
@ReiHashimoto 
取り急ぎ、以下のみ まず取り込んでいただく対応は、いかがでしょうか。
- https://github.com/arayabrain/barebone-studio/pull/40

※上記のみの個別対応は可能でしょうか？
※多少2度手間になるかもしれませんが、これ以外の改修項目では（WF import/exportはありますが）、for serverの初期リリースや要件へ影響あるものは、ないかと想定しています。

2023-09-07 11:45 UTC, ReiHashimoto commented
- #161 で手動で一部取り込みで対応

2023-09-07 11:45 UTC, closed without merging