fix pagination
arayabrain/optinist-for-server pull request #155
Opened 2023-09-06 07:12 UTC by sanglevinh

2023-09-06 07:41 UTC, itutu-tienday requested changes

2023-09-06 07:41 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
> +        .map((item: any) => `${item}=${(dataParamsFilter as any)[item]}`)
@sanglevinh 

Which issue is this correcting?
#143, right? However, it seems that the issue has not yet been resolved as follows.

![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/3f21664e-75ad-44ff-8f82-2ca36b504121)

2023-09-08 06:08 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseCells.tsx
> +        .map((item: any) => `${item}=${(dataParamsFilter as any)[item]}`)
@itutu-tienday this branch i created to fix the error when changing limit the number of records is showing wrong, params problem i fixed in PR https://github.com/arayabrain/optinist-for-server/pull/160

2023-09-12 10:01 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
> +        .map((item: any) => `${item}=${(dataParamsFilter as any)[item]}`)
@sanglevinh 
Let me check the status of this PR.
-> Is it assumed to be open or closed?

2023-09-13 02:42 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseCells.tsx
> +        .map((item: any) => `${item}=${(dataParamsFilter as any)[item]}`)
@itutu-tienday I have changed the open status to PR, please check it again

2023-09-13 03:59 UTC, ReiHashimoto approved these changes
LGTM

2023-09-13 04:01 UTC, itutu-tienday approved these changes

2023-09-13 04:02 UTC, merged