fix params
arayabrain/optinist-for-server pull request #160
Opened 2023-09-07 09:19 UTC by sanglevinh

2023-09-07 09:43 UTC, itutu-tienday requested changes
@sanglevinh 
We have verified that unnecessary URL parameters have been removed.

In addition, we have checked the behavior of the browser back, and the behavior does not seem to be appropriate, as shown below. 
Please check and adjust.

- Operation Example
  - Dashboard -> Database -> Browser back (NG)
  - Dashboard -> Workspaces -> Browser back (OK)
  - Dashboard -> Account Manager -> Browser back (NG)

- Relation
   - #151

2023-09-08 02:35 UTC, sanglevinh commented
> @sanglevinh We have verified that unnecessary URL parameters have been removed.
> 
> In addition, we have checked the behavior of the browser back, and the behavior does not seem to be appropriate, as shown below. Please check and adjust.
> 
> * Operation Example
>   
>   * Dashboard -> Database -> Browser back (NG)
>   * Dashboard -> Workspaces -> Browser back (OK)
>   * Dashboard -> Account Manager -> Browser back (NG)
> * Relation
>   
>   * [redirect関連の調整 #151](https://github.com/arayabrain/optinist-for-server/issues/151)
@itutu-tienday Regarding the browser back issue, I am handling it in another branch

2023-09-12 00:20 UTC, itutu-tienday approved these changes

2023-09-12 00:20 UTC, merged

2023-09-12 00:20 UTC, itutu-tienday commented
@sanglevinh 
This PR was still in Draft, but we opened it here and proceeded to merge.
If there is any remaining work, please let us know.