add cell attributes
arayabrain/optinist-for-server pull request #175
Opened 2023-09-12 09:43 UTC by ReiHashimoto

- cellの統計値を追加
  - cellのテーブルに統計値のカラムを追加(migrationが発生しているため、要`alembic upgrade head`)
  - バッチ処理でcellのレコードに統計値を保存
  - 統計値の表示をプロット画像に追加

- Dummyのfield処理
  - APIレスポンスではNoneとし、フロントではNAで表示(Experiments, Cellsいずれも対応)

![Screenshot 2023-09-12 at 18 39 39](https://github.com/arayabrain/optinist-for-server/assets/42664619/6d312e03-a78d-44f7-887d-6e34131fbad7)

2023-09-12 11:40 UTC, itutu-tienday commented
@ReiHashimoto 
こちらconflictがあるため、調整をお願いします

2023-09-12 12:53 UTC, ReiHashimoto commented
> @ReiHashimoto こちらconflictがあるため、調整をお願いします

conflictの修正、および一部レイアウトの修正を行いました。
attributeの表示対象が多く、cellのテーブルの高さが高くなってしまうため、一旦Polarとlineで表示するパラメータを分けました。

2023-09-12 13:22 UTC, itutu-tienday requested changes
@ReiHashimoto 
いくつか指摘事項を記載します

2023-09-12 13:22 UTC, itutu-tienday commented on studio/alembic/versions/5a565ec4961f_add_cell_attributes.py
> +def downgrade() -> None:
cellsの属性情報ですが、リリース初期や運用の中で項目の変動が想定されるため、JSON型のカラムで保持する形が、適当と考えます。

- 参考
  - https://zenn.dev/rescuenow/articles/854cf493737672

上記の想定ですが、もしカラムを個別に定義する必要がある事由があれば、お知らせください。

2023-09-12 13:22 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
> +      field: `graph_urls.${index}`,
暫定で、当ブランチにdevelop-main をマージした状態（最新想定環境）で解析バッチを動作させ、サイト表示したところ、添付イメージのように、パラメータの表示がすべて空となっているようでした。
※DBにはデータは正常に登録されているようでした

当方の環境の問題であることも想定されますが、ご確認をお願いします。

<img width="522" alt="image" src="https://github.com/arayabrain/optinist-for-server/assets/122338895/5ff71709-d15c-4b53-a0e0-b4d7f1ef741b">

2023-09-12 13:39 UTC, ReiHashimoto commented on frontend/src/components/Database/DatabaseCells.tsx
> +      field: `graph_urls.${index}`,
こちらでも最新版のdevelop-mainをmergeした状態で再度バッチ処理を実行して確認しましたが、再現せずでした...

![Screenshot 2023-09-12 at 22 33 40](https://github.com/arayabrain/optinist-for-server/assets/42664619/508a36f3-6f62-4f7c-9c32-06c2083bc646)

キーは出ているので問題ないはずですが、切り分けのため、
APIからのレスポンスが正常に返ってきているかご確認いただけますか？
cellsのエンドポイントのResponseで、graph_urls.paramsで各種valueが入っているか、の観点です。

![Screenshot 2023-09-12 at 22 36 35](https://github.com/arayabrain/optinist-for-server/assets/42664619/9c5aa050-77e4-4ac9-aa38-846a250acf91)

2023-09-12 14:14 UTC, ReiHashimoto commented on studio/alembic/versions/5a565ec4961f_add_cell_attributes.py
> +def downgrade() -> None:
json型のカラム`statistics`に変更しました。
統計値のフィールド追加のmigrationスクリプトごと削除していますので、
最新版pullの前に`alembic downgrade -1`を実行してください。

その後、pull → upgradeの流れでご対応をお願いします。

2023-09-12 23:39 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
> +      field: `graph_urls.${index}`,
@ReiHashimoto 
上記は、こちらの確認誤りでした。（確認対象データに誤り）
→ 再確認で、問題ないことを確認しました。 お手数おかけしました

2023-09-12 23:44 UTC, itutu-tienday requested changes

2023-09-12 23:44 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
> +              <Grid item xs={3}>
細かい指摘（要望）ですが、cells の params は、マウス操作でテキスト選択できるとよいと思いました。（ユーザビリティ）

もし簡易に対応可能であれば、調整検討いただければと思います。（優先度 低）
※セルにテキストドラッグできる余白を持たせる形（margin指定？）でも、まずはOKかと思います。

2023-09-13 00:50 UTC, ReiHashimoto commented on frontend/src/components/Database/DatabaseCells.tsx
> +              <Grid item xs={3}>
クリックして表示されるモーダル下部にパラメータ表示欄を設ける、でも良いかと思いましたがいかがでしょう?

2023-09-13 03:03 UTC, ReiHashimoto commented on frontend/src/components/Database/DatabaseCells.tsx
> +              <Grid item xs={3}>
cellの統計情報を顧客要望によりカラムへの表示と切り替えました。
この対応に伴い、本件は対応不要となる想定です。

2023-09-13 03:27 UTC, itutu-tienday approved these changes

2023-09-13 03:27 UTC, merged