Improve API Backend
arayabrain/optinist-for-server pull request #190
Opened 2023-09-15 04:14 UTC by quanpython

2023-09-21 10:47 UTC, itutu-tienday requested changes

2023-09-21 10:47 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
>              func.count(optinist_model.Cell.id).label("cell_count"),
@quanpython 
Doesn't this part need to be grouped by cells.experiment_uid?
→ Are the experiments currently being retrieved properly? (the aggregate results seem to be incorrect, please check)

2023-09-21 10:47 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +    if options.experiment_id:
@quanpython 
If I specify experiment_id as a query parameter (e.g. experiment_id=a), I get error 500.
\* No error occurs on the develop-main branch.

2023-09-21 10:47 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +    if options.experiment_id:
@quanpython 
Shouldn't this decision process be applied to the following similar APIs?
- /public/cells
- /expdb/experiments
- /expdb/cells

2023-09-21 10:47 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
>  @router.get(
@quanpython 
Is the cells API improving performance?
→ From what we have seen here, it does not seem to have improved (2-3 requests/sec).

2023-09-22 07:31 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +    if options.experiment_id:
@itutu-tienday Adding `group_by` solved this issue.

2023-09-22 07:31 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +    if options.experiment_id:
@itutu-tienday I applied it

2023-09-22 07:38 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
>  @router.get(
@itutu-tienday
Yes, it is 15 requests/sec on my machine with 100 experiments, 100.000 cells (1.000 cells per experiment).
Have you run migration successfully?

When I switch to your branch `improve-be-api-ex`, it is 7~8 requests/sec.

2023-09-22 08:33 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
>  @router.get(
@quanpython 
Once again, performance was checked with improve-be-api and improve-be-api-ex.

- public/experiments ... 12 req/sec performance is stable in this environment.
- public/cells ... 
  - In improve-be-api, the performance varied from 5 to 15 req/sec, but the performance was good.
  - improve-be-api-ex shows 2-3 req/sec performance

The above is the result, but once this is the case, I would like to proceed to APPROVE.

Could you please explain the effect of the two indexes added in improve-be-api-ex?

2023-09-22 11:53 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
>  @router.get(
@itutu-tienday

The two indexes added create separate data structure that stores a sorted list of the values in those columns along with pointers to the corresponding rows in the table. This allows the database to quickly locate the rows that match the conditions in the query without scanning the entire table.
`FORCE INDEX FOR JOIN` and `USE INDEX` makes sure the index is used as desired.
But in count query, `FORCE INDEX FOR JOIN` and `USE INDEX` is not a good option to improve the performance, that is why I created the branch https://github.com/arayabrain/optinist-for-server/tree/improve-be-api2, which shows 40 requests/sec performance

2023-09-25 01:39 UTC, itutu-tienday requested changes

2023-09-25 01:39 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
>  @router.get(
@quanpython 
Thank you.

As a result of the review, we are assuming the adoption of `improve-be-api2`, but we would appreciate your response and action on the following two points.

- Please include technical comments (reasons for changing the functionality of the library) in the customized implementation of `improve-be-api2`.
- Also, for the index key `cells_id_created_at_updated_at_index`, does this need to be updated each time the API response data item changes? (For operational considerations, we would like to avoid frequent regeneration of the index key.)

2023-09-25 14:17 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
>  @router.get(
@itutu-tienday
> Please include technical comments (reasons for changing the functionality of the library) in the customized implementation of improve-be-api2.

I added it in ce93643

> Also, for the index key `cells_id_created_at_updated_at_index`, does this need to be updated each time the API response data item changes?

If you modify the query fields, you need analyze the execution plan again to optimize it. It might be required to update the index key accordingly.

2023-09-26 04:35 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
>  @router.get(
@quanpython 
> I added it in ce93643
Thak you.

> If you modify the query fields, you need analyze the execution plan again to optimize it. It might be required to update the index key accordingly.

Understood. We will incorporate the content so far once we are done, and maintenance of the index will be an operational note.

2023-09-26 08:53 UTC, itutu-tienday approved these changes

2023-09-26 08:54 UTC, merged

2023-09-27 05:52 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +        .filter(
@quanpython 
Is this filter a duplicate of the code added on line 233? (Shouldn't this be removed?)