add autoFocus to input when filter, fix time filter 300 -> 500
arayabrain/optinist-for-server pull request #214
Opened 2023-10-16 06:43 UTC by sanglevinh

2023-10-16 09:06 UTC, itutu-tienday requested changes

2023-10-16 09:06 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
> +                }, 500)
@sanglevinh 
This is a minor point, but could you please keep this (waiting time) as a constant?

2023-10-16 23:55 UTC, itutu-tienday requested changes

2023-10-16 23:55 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +          operator: ['publish_status', 'brain_area'].includes(Object.keys(dataParamsFilter).find(key => (dataParamsFilter as any)[key]) || 'publish_status') ? 'is' : 'contains',
@sanglevinh 
The "No_published" in publish_status does not seem to be working. Please reconfirm.

2023-10-17 01:52 UTC, itutu-tienday commented
@sanglevinh 
Just a reminder, this PR has over 2,000 commits (due to rebase?). Is there any problem with this?

2023-10-17 03:06 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +          operator: ['publish_status', 'brain_area'].includes(Object.keys(dataParamsFilter).find(key => (dataParamsFilter as any)[key]) || 'publish_status') ? 'is' : 'contains',
@itutu-tienday I have reported to BE and it has been fixed, please check again

2023-10-17 03:06 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseCells.tsx
> +                }, 500)
@itutu-tienday i have added it

2023-10-17 03:18 UTC, sanglevinh commented
> @sanglevinh Just a reminder, this PR has over 2,000 commits (due to rebase?). Is there any problem with this?

@itutu-tienday Because I am using rebase, there is no issue with it.

2023-10-17 04:38 UTC, itutu-tienday approved these changes

2023-10-17 04:38 UTC, merged