Fix default sort option
arayabrain/optinist-for-server pull request #222
Opened 2023-10-17 10:42 UTC by quanpython

2023-10-18 01:57 UTC, itutu-tienday requested changes

2023-10-18 01:57 UTC, itutu-tienday commented on studio/app/optinist/schemas/base.py
> +        default=None,
@quanpython 
At PR #217, I was aware that functional modifications were being made,
1. is this fix a degrade?
2. or was the functionality (sorting by experiment_id) not originally built in?

2023-10-18 01:57 UTC, itutu-tienday commented on studio/app/optinist/schemas/base.py
> +        sort = (
@quanpython 
This fix appears to be degrading the performance of the GET cells API.
The requirement also mentions ensuring the performance of the API, has this been addressed?

2023-10-18 06:34 UTC, quanpython commented on studio/app/optinist/schemas/base.py
> +        sort = (
@itutu-tienday
This fix doesnt degrade the performance of the GET cells API. 
Previously, APIs were being sorted by Cell ID by default, when the query was optimized, while sort by Experiment column is not.
Sorting by fields of Cell and Experiment tables is showing different performance, because the index key needed to optimize is different.

I've added the condition checks to handle them.

2023-10-18 07:22 UTC, itutu-tienday commented on studio/app/optinist/schemas/base.py
> +        sort = (
@quanpython 
> Previously, APIs were being sorted by Cell ID by default, when the query was optimized, while sort by Experiment column is not.

Are you saying that in some cases the sort(order by) condition changed due to optimization of the query?
Also, is it OK to say that now the default is definitely sorted by experiment_id?

> Sorting by fields of Cell and Experiment tables is showing different performance, because the index key needed to optimize is different.

Thanks. With the latest commit, I have confirmed that the performance of the GET cells API has returned to the same level as before. (15-20 req/sec)

2023-10-18 10:31 UTC, quanpython commented on studio/app/optinist/schemas/base.py
> +        sort = (
@itutu-tienday
> Are you saying that in some cases the sort(order by) condition changed due to optimization of the query?

I mean the performance of query changed due to the sort condition. Because "id" and "experiment_id" are in different table.

> Also, is it OK to say that now the default is definitely sorted by experiment_id?

Yes.

2023-10-19 04:10 UTC, itutu-tienday approved these changes

2023-10-19 04:10 UTC, merged