Feature: Group API
arayabrain/optinist-for-server pull request #228
Opened 2023-10-25 03:43 UTC by quanpython

2023-10-26 02:22 UTC, ReiHashimoto requested changes

2023-10-26 02:22 UTC, ReiHashimoto commented on studio/app/common/schemas/users.py
> +    group_ids: List[int]
Could you update group_ids to be optional in request body?
(on UserUpdate, too.)
If this value is not provided,
- group_ids is empty list (on create)
- group_ids are kept as it is (on update)

CC: @itutu-tienday
こちらの仕様への修正で良いでしょうか？

2023-10-26 02:41 UTC, itutu-tienday commented on studio/app/common/schemas/users.py
> +    group_ids: List[int]
@ReiHashimoto 
A few comments.

> group_ids are kept as it is (on update)

I think it would be better to keep it in line with the update behavior of the other items (name, email, ).
\* Are name, email updated every time? (need to check)

2023-10-26 03:24 UTC, ReiHashimoto commented on studio/app/common/schemas/users.py
> +    group_ids: List[int]
@itutu-tienday 
currently, 
- optional
  - email
- required
  - name
  - role_id

required params are updated every time.
I think all params in this model should be optional on update to prevent unintended field updates.

2023-10-26 04:44 UTC, itutu-tienday commented on studio/app/common/schemas/users.py
> +    group_ids: List[int]
@ReiHashimoto 
- I checked the source.
  - I see that email is optional in BE, but in `PUT /admin/user`, it is effectively treated as a required field.

Based on the above, let's rearrange it as follows.

- Target API is `PUT /admin/user`.
  - On the FE side, unchanged fields are sent to BE with empty.
  - On the BE side, fields sent as empty are not subject to update.
- Target fields are all fields of Edit Account form.

2023-10-26 05:41 UTC, ReiHashimoto commented on studio/app/common/schemas/users.py
> +    group_ids: List[int]
@itutu-tienday 
Thank you.
It is likely that similar problems exist with other APIs, so resolve them in another issue.

2023-10-26 07:22 UTC, itutu-tienday requested changes

2023-10-26 07:22 UTC, itutu-tienday commented on studio/alembic/versions/51fca12beea5_add_group_organization_id.py
> +"""add group organization_id
@quanpython 
Regarding alembic/versions, can you please consolidate them into one file within this development PR? (For the purpose of brevity in version control)

2023-10-27 03:21 UTC, quanpython commented on studio/alembic/versions/51fca12beea5_add_group_organization_id.py
> +"""add group organization_id
@itutu-tienday
I implemented it

2023-10-27 07:39 UTC, itutu-tienday requested changes

2023-10-27 07:39 UTC, itutu-tienday commented on studio/app/common/core/users/crud_groups.py
> +                GroupModel.name.like("%{0}%".format(keyword)),
@quanpython 
If keyword is empty, the record cannot be retrieved.
If keyword is empty, please exclude the where condition. (Same as other APIs)

2023-10-30 03:50 UTC, itutu-tienday requested changes

2023-10-30 03:50 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +    for exp in exps:
@quanpython 
I think it would be more efficient to use a form of batch update (like update-select) at the SQL level, rather than sequential updates in a loop here.
\* If visibility of the code is a priority, I think this form is acceptable at this time.

2023-10-30 05:51 UTC, quanpython commented on studio/app/common/core/users/crud_groups.py
> +                GroupModel.name.like("%{0}%".format(keyword)),
@itutu-tienday
Do you want to raise validation error if the client sends an empty string? If so, there is no need to exclude the where condition

2023-10-30 06:05 UTC, itutu-tienday commented on studio/app/common/core/users/crud_groups.py
> +                GroupModel.name.like("%{0}%".format(keyword)),
@quanpython 
Currently, if keywords are not specified in the http GET query, no records are retrieved. (Because LIKE is always specified.)
-> Groups does not have a large number of records, so in the above case, please keep all Groups as the search target.

2023-10-30 07:00 UTC, quanpython commented on studio/app/common/core/users/crud_groups.py
> +                GroupModel.name.like("%{0}%".format(keyword)),
@itutu-tienday
I changed the default value of keyword to empty string and it works as expect.
Please check it.

2023-10-30 12:37 UTC, ReiHashimoto requested changes

2023-10-30 12:37 UTC, ReiHashimoto commented on studio/app/optinist/routers/expdb.py
> +        query = (
when current_user's role is operator, `expdb/cells` returns "total": 0.
but items are correct.
could you research on this?

2023-10-31 02:23 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +        query = (
@ReiHashimoto
Sorry. It was my fault for not updating `total_query`.
I have fixed it.

2023-10-31 02:32 UTC, ReiHashimoto approved these changes

2023-10-31 05:39 UTC, itutu-tienday approved these changes

2023-10-31 07:38 UTC, merged