Update account edit API
arayabrain/optinist-for-server pull request #232
Opened 2023-10-27 07:20 UTC by quanpython

2023-10-30 02:33 UTC, itutu-tienday requested changes

2023-10-30 02:33 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        user_data = data.dict(exclude_unset=True, exclude_defaults=True)
@quanpython 
A minor confirmation,
Since the `class UserUpdate` specifies Optional for each field, I think it is possible to access the None field with user_data.{fieldname} without using `user_data.pop`, right?
Please let me know if I am wrong.

2023-10-30 02:36 UTC, itutu-tienday commented
@ReiHashimoto 
当件、念のため確認しておいていただければと思います。

2023-10-30 02:51 UTC, ReiHashimoto commented on studio/app/common/core/users/crud_users.py
> +        user_data = data.dict(exclude_unset=True, exclude_defaults=True)
Strictly speaking,
without using `user_data = data.dict`,
`data.{fieldname}` is enough.

2023-10-30 10:13 UTC, quanpython commented on studio/app/common/core/users/crud_users.py
> +        user_data = data.dict(exclude_unset=True, exclude_defaults=True)
@itutu-tienday
Yes, it is possible to access the None field with user_data.{fieldname} without using user_data.pop.

The purpose of using `pop` is to remove fields that do not exist in the User Model.
Then I will loop through the remaining fields to assign to the User Model with the `setattr` method (this will be convenient if the User Model has many fields that need to be edited).

If modifications are needed please let me know.

2023-10-30 11:24 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        user_data = data.dict(exclude_unset=True, exclude_defaults=True)
@quanpython 
> The purpose of using pop is to remove fields that do not exist in the User Model.

Understood, the current configuration seems fine.

2023-10-30 12:15 UTC, ReiHashimoto approved these changes
LGTM

2023-10-31 05:38 UTC, itutu-tienday approved these changes

2023-10-31 05:38 UTC, merged