Feature/group manager
arayabrain/optinist-for-server pull request #233
Opened 2023-10-27 07:58 UTC by sanglevinh

2023-10-27 09:58 UTC, ReiHashimoto requested changes

2023-10-27 09:58 UTC, ReiHashimoto commented on frontend/src/components/PopupShareGroup.tsx
> +      else if(newUserIds.length > 0 || newListGroups.length > 1) newType = SHARE.USERS
Wouldn't `newListGroups.length > 0` be correct?

2023-10-27 09:58 UTC, ReiHashimoto commented on frontend/src/components/PopupShareGroup.tsx
> +  const handleOke = async () => {
Typo? 
→ handleOk

2023-10-27 09:58 UTC, ReiHashimoto commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                        <PublicOffIcon onClick={() => handleOpenPublishAll(`Unpublish ${listCheck.length} records at once. Is this OK?`, 'off')} />
- wrap each Icon with IconButton and move onClick to the IconButton component.
- use size or fontSize "large"
- use button's color "primary"

2023-10-27 09:58 UTC, ReiHashimoto commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    width: 160,
width looks too wide.
could you make it narrower?

2023-10-27 10:12 UTC, ReiHashimoto requested changes

2023-10-27 10:12 UTC, ReiHashimoto commented on frontend/src/components/common/PopupConfirm.tsx
> +      </DialogTitle>
Use DialogContent and Typography since the message you are passing looks the body rather than the title.

2023-10-27 10:12 UTC, ReiHashimoto commented on frontend/src/pages/Administration/index.tsx
> +                <ManageAccountsIcon fontSize="large" />
Changing Icons may be preferred.
- account-manager -> Person
- group-manager ->Group

2023-10-27 10:12 UTC, ReiHashimoto commented on frontend/src/pages/GroupManager/index.tsx
> +}))
Any reason for not using MUI IconButton?

2023-10-30 03:00 UTC, itutu-tienday requested changes

2023-10-30 03:00 UTC, itutu-tienday commented on frontend/src/components/PopupSetGroupManager.tsx
> +              <KeyboardBackspaceIcon
@sanglevinh
Only records selected in the right pane should be moved from right to left.
(The same explanation has been added to Screen Design v1.1)

2023-10-30 03:11 UTC, sanglevinh commented on frontend/src/components/PopupShareGroup.tsx
> +      else if(newUserIds.length > 0 || newListGroups.length > 1) newType = SHARE.USERS
@ReiHashimoto sorry, newListGroups.length > 0 is correct and newListGroups.length > 0, I fixed it

2023-10-30 03:11 UTC, sanglevinh commented on frontend/src/components/PopupShareGroup.tsx
> +  const handleOke = async () => {
@ReiHashimoto i fixed it

2023-10-30 03:12 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                        <PublicOffIcon onClick={() => handleOpenPublishAll(`Unpublish ${listCheck.length} records at once. Is this OK?`, 'off')} />
@ReiHashimoto i fixed it

2023-10-30 03:12 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    width: 160,
@ReiHashimoto i fixed it (width: 70)

2023-10-30 03:13 UTC, sanglevinh commented on frontend/src/components/common/PopupConfirm.tsx
> +      </DialogTitle>
@ReiHashimoto i fixed it

2023-10-30 03:13 UTC, sanglevinh commented on frontend/src/pages/Administration/index.tsx
> +                <ManageAccountsIcon fontSize="large" />
@ReiHashimoto i fixed it

2023-10-30 03:14 UTC, sanglevinh commented on frontend/src/pages/GroupManager/index.tsx
> +}))
@ReiHashimoto Because when using Mui's Button, there is sometimes a UI error, but I have already fixed it to Button

2023-10-30 03:20 UTC, ReiHashimoto commented on frontend/src/pages/GroupManager/index.tsx
> +}))
@sanglevinh 
For future reference, can you tell us specifically what the UI error was?

2023-10-30 04:38 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@ReiHashimoto 
以下の部分のアイコン表示切替ですが、現在 visibility 自体を on/off していますが、やはり表示のon/offでは やや分かりづらくはないか、とも感じています。
enabled の on/off (offでグレーアウト) では、どうでしょうか。（やはりoffで非表示がよさそうでしょうか）
![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/09f30211-452d-46c6-99e5-f2f00c1d0020)

2023-10-30 04:39 UTC, sanglevinh commented on frontend/src/pages/GroupManager/index.tsx
> +}))
@ReiHashimoto Sometimes it will show the hover color even though there is no hover over it, I've had that error with MUI Buttons elsewhere so I just used 'button'

2023-10-30 04:44 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                        <PublicOffIcon onClick={() => handleOpenPublishAll(`Unpublish ${listCheck.length} records at once. Is this OK?`, 'off')} />
@ReiHashimoto 
Sorry, I missed 1 exploit point in this exploit. I will report back to you after fixing it

2023-10-30 04:46 UTC, itutu-tienday requested changes

2023-10-30 04:46 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                          <PublicIcon onClick={() => handleOpenPublishAll(`Publish ${listCheck.length} records at once. Is this OK?`, 'on')} />
@sanglevinh 
Could you add a caption to the confirmation dialog?
-> "Bulk Publish"

![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/1a148e4d-2c50-4b2d-afdc-ffd93fd60af1)

2023-10-30 04:46 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                          <PublicOffIcon onClick={() => handleOpenPublishAll(`Unpublish ${listCheck.length} records at once. Is this OK?`, 'off')} />
@sanglevinh 
Could you add a caption to the confirmation dialog?
-> "Bulk UnPublish"

2023-10-30 04:56 UTC, itutu-tienday requested changes

2023-10-30 04:56 UTC, itutu-tienday commented on frontend/src/components/PopupShareGroup.tsx
> +        title={`Update the share settings of ${listCheck?.length} records at once. Is this OK?`}
@sanglevinh 
Could you add a caption to the confirmation dialog?
-> "Bulk Update"

- resemble
  - https://github.com/arayabrain/optinist-for-server/pull/233/files#r1375666384

2023-10-30 04:59 UTC, sanglevinh commented on frontend/src/components/PopupShareGroup.tsx
> +        title={`Update the share settings of ${listCheck?.length} records at once. Is this OK?`}
@itutu-tienday yes, i will add it

2023-10-30 04:59 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                          <PublicOffIcon onClick={() => handleOpenPublishAll(`Unpublish ${listCheck.length} records at once. Is this OK?`, 'off')} />
@itutu-tienday yes, i will add it

2023-10-30 04:59 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                          <PublicIcon onClick={() => handleOpenPublishAll(`Publish ${listCheck.length} records at once. Is this OK?`, 'on')} />
@itutu-tienday yes, i will add it

2023-10-30 05:00 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                (<WrapperIcons>
@sanglevinh 
Please display tooltips (on mouse hover) for each icon.
- share icon ... "bulk share".
- publish icon ... "bulk publish"
- unpublish icon ... "bulk unpublish"

2023-10-30 05:09 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@itutu-tienday I still don't quite understand, do you mean that these 3 icons will always appear, but when clicking on a record, it will have the 'primary' color and if no record is selected, it will have the default color (black) right?

2023-10-30 05:21 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@sanglevinh 
My apologies. The above was a confirmation message to our member once.
The specifications are as you described above. (Not black, but a light gray image)
We will adjust the specifications and let you know again.

2023-10-30 05:34 UTC, itutu-tienday commented on frontend/src/pages/AccountManager/index.tsx
@sanglevinh 
The title ("Account Manager") should appear in the upper left corner of the Account Manager screen.
(as on the Group Manager screen)

2023-10-30 05:36 UTC, ReiHashimoto commented on frontend/src/pages/GroupManager/index.tsx
> +}))
@sanglevinh 
I have tried replacing it with IconButton in my environment, but it does not seem to reproduce.
Is this still occurring in your environment?

2023-10-30 05:38 UTC, ReiHashimoto commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@itutu-tienday 
UIに関してはどうしても個人で捉え方が変わってしまいますね。
表示のon/offについて、絶対にこの方が良いと言うほどのものではないので、記載の方針でOKです。

2023-10-30 05:49 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@ReiHashimoto 
了解です。重要な部分ではありませんが、ユーザー問い合わせを抑える意図で、ここは一旦グレーアウトとしておこうと思います。

@sanglevinh 
Please use the following specifications for the above.
- When no record is selected
  - Currently) Hide each icon of bulk operation
  - Update) Make each icon of bulk operation disabled (inoperable, grayed out)

2023-10-30 05:53 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@ReiHashimoto @itutu-tienday So I'll keep it as it is

2023-10-30 06:02 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
@itutu-tienday i added it, pls check it again

2023-10-30 06:02 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                (<WrapperIcons>
@itutu-tienday i added it, pls check it again

2023-10-30 06:02 UTC, sanglevinh commented on frontend/src/components/PopupShareGroup.tsx
> +        title={`Update the share settings of ${listCheck?.length} records at once. Is this OK?`}
@itutu-tienday i added it, pls check it again

2023-10-30 06:02 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                          <PublicOffIcon onClick={() => handleOpenPublishAll(`Unpublish ${listCheck.length} records at once. Is this OK?`, 'off')} />
@itutu-tienday i added it, pls check it again

2023-10-30 06:03 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                          <PublicIcon onClick={() => handleOpenPublishAll(`Publish ${listCheck.length} records at once. Is this OK?`, 'on')} />
@itutu-tienday i added it, pls check it again

2023-10-30 06:04 UTC, sanglevinh commented on frontend/src/components/PopupSetGroupManager.tsx
> +              <KeyboardBackspaceIcon
@itutu-tienday I have adjusted according to the latest spec to only add each selected user

2023-10-30 06:05 UTC, sanglevinh commented on frontend/src/components/PopupSetGroupManager.tsx
> +    <div>
@itutu-tienday I have updated it, pls check it again

2023-10-30 06:06 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                        <PublicOffIcon onClick={() => handleOpenPublishAll(`Unpublish ${listCheck.length} records at once. Is this OK?`, 'off')} />
@itutu-tienday I have fixed it, pls check it again

2023-10-30 06:25 UTC, itutu-tienday requested changes

2023-10-30 06:25 UTC, itutu-tienday commented on frontend/src/pages/AccountManager/index.tsx
@sanglevinh 
The title here should be "Account Manager".
* In my environment, it appears to be "Group Manager".

2023-10-30 06:44 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
@itutu-tienday Very sorry about this small problem, I have fixed it

2023-10-30 06:45 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@ReiHashimoto @itutu-tienday i fixed it, pls check it again

2023-10-30 06:46 UTC, sanglevinh commented on frontend/src/pages/GroupManager/index.tsx
> +}))
@ReiHashimoto 
I have already changed it to MUI's Button and it seems to have no problem at all

2023-10-30 07:02 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@sanglevinh 
thank you.
I have checked, but would like to make some more adjustments below.

- When no record is selected,
  - Make each icon of bulk operation disabled (inoperable, grayed out (light gray))
    - Currently, the bulk operation is not disabled and the black button can be pressed.

2023-10-30 07:34 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@itutu-tienday yes, I blocked that when no experiment was selected

2023-10-30 07:47 UTC, itutu-tienday commented on frontend/src/components/PopupSetGroupManager.tsx
> +            <Box style={{position: 'relative', flex: 1, maxWidth: '45%', alignSelf: 'start', height: '100%' }}>
@sanglevinh 
Currently, the right pane (Search users) has the following operating specifications

1. search for users in the search box -> search results are displayed in the pull-down menu. 
2. click the search result of 1. and display the record in the table in the right pane.
3. select a record in the table in 2. and move it to the left pane.

I would like to adjust this to the following specifications.

1. search for users in the search box → search results are reflected in the table in the right pane.
2. select a record in table 1. and move it to the left pane.

--
If there are any implementation issues or questions regarding the above, please contact us.

2023-10-30 07:55 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
> +                  <SelectError
@itutu-tienday i added it

2023-10-30 08:14 UTC, sanglevinh commented on frontend/src/components/PopupSetGroupManager.tsx
> +            <Box style={{position: 'relative', flex: 1, maxWidth: '45%', alignSelf: 'start', height: '100%' }}>
@itutu-tienday I want to confirm, I can only select 1 record from the right table at a time to move to, right?

2023-10-30 08:46 UTC, itutu-tienday commented on frontend/src/components/PopupSetGroupManager.tsx
> +            <Box style={{position: 'relative', flex: 1, maxWidth: '45%', alignSelf: 'start', height: '100%' }}>
@sanglevinh 
Yes, that is the assumption.

The intent of this modification request is to reduce the number of steps to operate the right pane.
\* Currently, the user search results are displayed once in a pull-down, but I would like to set this directly to the table in the right pane.

2023-10-30 08:54 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@sanglevinh 
I think the operation is OK.

One point, please make the following adjustments.
> icon disabled (grayed out (light gray))

2023-10-30 09:04 UTC, sanglevinh commented on frontend/src/components/PopupSetGroupManager.tsx
> +            <Box style={{position: 'relative', flex: 1, maxWidth: '45%', alignSelf: 'start', height: '100%' }}>
@itutu-tienday I understand that, but what I want to ask is whether we can select multiple records to move to the left table or can we only select 1 record each time we move.

2023-10-30 09:17 UTC, ReiHashimoto commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@sanglevinh 
The points are, 
- hover action is misleading (looks clickable).
- gray color is more understandable that the button is disabled than black.

How about implementation like this?
I think it's simpler.

```
const bulkDisabled = listCheck.length === 0

return (
  <DatabaseExperimentsWrapper>
    {user ? (
      <Box>
        {adminOrManager ? (
          <Box display="flex" justifyContent="end">
            <Tooltip title={'bulk share'} placement={'top'}>
              <span>
                <IconButton
                  size="large"
                  disabled={bulkDisabled}
                  color="primary"
                  onClick={() => setOpenShareGroup(true)}
                >
                  <GroupAddIcon fontSize="large" />
                </IconButton>
              </span>
            </Tooltip>
...
```

- using IconButton and disabled property. It automatically
  - prevents hover action
  - change color to be disabled

2023-10-30 09:17 UTC, itutu-tienday commented on frontend/src/components/PopupSetGroupManager.tsx
> +            <Box style={{position: 'relative', flex: 1, maxWidth: '45%', alignSelf: 'start', height: '100%' }}>
@sanglevinh 
Moving from right to left is Good with one item at a time operation (same as current implementation).

\* However, if it can be implemented simply, it would be appreciated if it is possible to move multiple selected items from right to left.

2023-10-30 09:28 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@ReiHashimoto i fixed it, pls check it again

2023-10-30 11:16 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +                    listCheck.length > 0 ? (
@sanglevinh 
Thank you.
I have applied the tweak here, so please pull it.

- https://github.com/arayabrain/optinist-for-server/pull/233/commits/43c68478a1fb14776aee2c1a9a8ed1bfa0bef681

2023-10-30 11:48 UTC, itutu-tienday commented on frontend/src/pages/GroupManager/index.tsx
> +    filterable: true,
@sanglevinh 
The search in the name field does not appear to be working, please fix.

2023-10-30 12:47 UTC, sanglevinh commented on frontend/src/pages/GroupManager/index.tsx
> +    filterable: true,
@itutu-tienday According to the previous spec and QA, the filter feature will not be available yet, I will hide it

2023-10-31 02:07 UTC, itutu-tienday commented on frontend/src/components/PopupSetGroupManager.tsx
> +                  <DataGrid
@sanglevinh 
It seems that deleting a record already registered to the left pane makes it impossible to search in the right pane.
- I would like the deleted records to be searchable.
- It seems that data can be retrieved from the right pane API, so it seems to be excluded by frontend.

2023-10-31 02:09 UTC, itutu-tienday commented on frontend/src/components/PopupSetGroupManager.tsx
> +                  <DataGrid
@sanglevinh 
When communicating API from the right pane, the loading icon should be displayed.

2023-10-31 03:27 UTC, sanglevinh commented on frontend/src/components/PopupSetGroupManager.tsx
> +                  <DataGrid
@itutu-tienday I'm thinking that, if I register a user to the left, the right will be discarded and not found anymore to avoid manipulating previously registered users.

2023-10-31 03:37 UTC, sanglevinh commented on frontend/src/components/PopupSetGroupManager.tsx
> +                  <DataGrid
@itutu-tienday I added loading when the user searches here, but when the load is too fast it will look like it's flashing

2023-10-31 04:21 UTC, itutu-tienday commented on frontend/src/components/PopupSetGroupManager.tsx
> +                  <DataGrid
@sanglevinh 
thank you. for now, this is ok.

2023-10-31 04:41 UTC, itutu-tienday commented on frontend/src/components/PopupSetGroupManager.tsx
> +                  <DataGrid
@sanglevinh 
Thanks.
I think what you suggest would work fine, but ideally I am thinking of the following behavior.

- pattern 1) The user appears in the position in which they are actually set up (left pane or right pane or unregistered)
- pattern 2) If the user is already registered in the left pane, that's will also appear in the right pane. 
  - → However, in the right pane, a mark is added to indicate that the user has already been registered.

That is all, but if it takes some time to fix the problem, we will release the system with the current specifications for the time being, as we plan to release the system this evening.

2023-10-31 04:47 UTC, ReiHashimoto approved these changes

2023-10-31 06:55 UTC, sanglevinh commented on frontend/src/components/PopupSetGroupManager.tsx
> +                  <DataGrid
@itutu-tienday I have added an icon for each added user in the left panel, pls check it again

2023-10-31 07:05 UTC, itutu-tienday commented on frontend/src/components/PopupSetGroupManager.tsx
> +                  <DataGrid
@sanglevinh 
As expected, thanks for the response.

2023-10-31 07:22 UTC, itutu-tienday commented
@sanglevinh 
I think you have almost completed this PR, so if there are no other remaining tasks, please set the status to open.

2023-10-31 07:38 UTC, itutu-tienday approved these changes

2023-10-31 07:38 UTC, merged