update Dockerfile for development
arayabrain/optinist-for-server pull request #242
Opened 2023-11-13 07:06 UTC by itutu-tienday

merge updates in Dokerfile (production)

2023-11-13 07:13 UTC, itutu-tienday commented
@ReiHashimoto 
こちら、レビューをお願いします。

■数点、認識課題
- installation docs のアップデートが必要
  - 別紙でまとめられているが、リポジトリ内の docs のアップデートも行っておくのがよい
- Ubuntu環境によっては、docker container 内の uid/gid と、docker host 内の uid/gid が一致しない環境がある？
  - 例） container: uid=500 だが、mount dir にファイル出力すると、host上では uid=100499 となっているケースがある。
    - `- 10001` が適用されている。

2023-11-13 07:39 UTC, ReiHashimoto requested changes

2023-11-13 07:39 UTC, ReiHashimoto commented on studio/config/docker/Dockerfile.dev
> +# add operatinal user
細かい点で恐縮ですが、
operational
でしょうか。

2023-11-13 07:39 UTC, ReiHashimoto commented on docker-compose.dev.yml
動作の想定条件について確認が必要そうです。

現状、studio-dev-beについて、volumesの調整が必要かと思います。
studio/config/.envのEXPDB_DIR, PUBLIC_EXPDB_DIRとして設定するディレクトリをコンテナから参照可能にする必要がありそうです。

docker-composeコマンドの際に渡すようにするのでしたっけ？

2023-11-14 10:05 UTC, itutu-tienday commented on docker-compose.dev.yml
@ReiHashimoto 
若干、構成を調整しています。

なおホストのディレクトリをroot外でmountする場合は、やはり一定の細かな調整を要します。
開発版なのでroot運用でも問題はありませんが、当システムではWEBアプリとバッチプログラムが連動しているため、あえて開発時からパーミッションを意識させる構成としています。

また以下、当システムでディレクトリmountに関する課題・制限事項を、備忘記載します。

- データはホスト側で投入することを想定している。
  - → ホスト側でも、適切なパーミッション指定が必要
- docker container初回起動時に、すでに生成済のディレクトリ（repository中のディレクトリ）と、未生成のディレクトリが混在する。（logs/ など）
- OSにより、ディレクトリmount時のパーミッション構成の仕様が異なる。（Mac/Ubuntuで異なる）
- Ubuntu環境によっては、docker containerとhost で、uid/gid が揃わないケースがある模様。
  - → 上記の状態が明確に解消されない限りは、書込の発生するmount先ディレクトリは、すべて `chown 777` としておく必要がある。

なお上記の課題は、初回docker環境構築前に以下を事前準備することで概ね回避できるため、現時点では別途構築手順に記載する対処としようと考えています。（全自動化が望ましいですが…）

```bash
# 初回 docker compose up 前に以下を実施
cd {OPTINIST_SRC_DIR}
mkdir .snakemake ../experiments_datasets ../experiments_public
sudo chmod 777 logs .snakemake ../experiments_datasets ../experiments_public
```

一旦以上ですが、ご指摘あればお願いします。

2023-11-15 04:14 UTC, ReiHashimoto commented on docker-compose.dev.yml
@itutu-tienday 
修正ありがとうございます。
現状の課題について、承知いたしました。
一旦は開発版のコンテナの構成としてはOKかと思います。

なお、mount先のコンテナ内のディレクトリ名が/data/experiments_datasets, /data/experiments_publicであることから、.env.exampleのEXPDB_DIR, PUBLIC_EXPDB_DIRの初期値をこれらに揃えるようにしました。

2023-11-15 04:14 UTC, ReiHashimoto approved these changes

2023-11-16 04:10 UTC, itutu-tienday commented on docker-compose.dev.yml
@ReiHashimoto 
ありがとうございます。
一旦の対応ですが、docker-compose.dev.yml にコメント追記する対応としています。（セットアップ時の事前のディレクトリ作成について）

2023-11-16 04:10 UTC, merged