Improve get public cells with high offset
arayabrain/optinist-for-server pull request #244
Opened 2023-11-20 02:44 UTC by quanpython

2023-11-27 03:46 UTC, itutu-tienday requested changes

2023-11-27 03:46 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> -    query = select(
@quanpython 
(This is not a suggestion for this function, but)
please exclude the "cell_count" aggregation in the following areas to speed up the process.
- https://github.com/arayabrain/optinist-for-server/pull/244/files#diff-f1cd2bead64ad5d03e4d4a4bf30c8b9b50d605bf51f1c1c40aac72b8d8efb038R143

2023-11-27 03:46 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> -    query = select(
@quanpython 
(This is not a suggestion for this function, but)
Does the following code work?
- https://github.com/arayabrain/optinist-for-server/pull/244/files#diff-f1cd2bead64ad5d03e4d4a4bf30c8b9b50d605bf51f1c1c40aac72b8d8 efb038r152

*Because the raw SQL always seems to contain `experiments.experiment_id LIKE '%%'` (does it reproduce in your environment?)

2023-11-27 09:05 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> -    query = select(
@itutu-tienday
Sorry, this case has not been covered yet. If experiment_id is not passed, the default value is the empty string.

But the query performance with and without `LIKE "%%"` is equivalent. Does this part need editing?

2023-11-28 03:59 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> -    query = select(
@quanpython 
If there is no definite impact on query performance, we would consider it OK to leave it as it is at present.

2023-11-28 04:08 UTC, itutu-tienday approved these changes

2023-11-28 04:08 UTC, merged