merge barebone
arayabrain/optinist-for-server pull request #245
Opened 2023-12-11 02:24 UTC by ReiHashimoto

merge barebone-studio's updates into this repository

2023-12-11 06:47 UTC, itutu-tienday requested changes

2023-12-11 06:47 UTC, itutu-tienday commented on frontend/.env.example
> +
起動直後、FEで以下の様なReactのコンパイルエラーが発生しています。
何らか環境セットアップ手順などに問題ありそうでしょうか？

```
[eslint] 
src/api/database/index.ts
  Line 1:73:   Strings must use doublequote                                                   quotes
  Line 2:1:    There should be at least one empty line between import groups                  import/order
  Line 2:19:   Strings must use doublequote                                                   quotes
  Line 3:1:    `qs` import should occur before import of `store/slice/Database/DatabaseType`  import/order

〜〜 他、全体的にlint error が発生の模様 〜〜
```

2023-12-11 06:47 UTC, itutu-tienday commented on frontend/.env.example
> +
また起動直後、BE側でも以下のような起動エラーが発生。
環境セットアップの問題？

```
2023-12-11 15:42:08,015 ERROR:    run_asgi():433 - Exception in ASGI application
Traceback (most recent call last):
  File "/home/iam/miniconda3/envs/optinist-for-server_dev/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]

〜〜〜〜

  File "/home/iam/miniconda3/envs/optinist-for-server_dev/lib/python3.8/site-packages/fastapi/routing.py", line 145, in serialize_response
    raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 2 validation errors for ExptConfig
response -> 4109baa7 -> nwb
  none is not an allowed value (type=type_error.none.not_allowed)
response -> 4109baa7 -> snakemake
  none is not an allowed value (type=type_error.none.not_allowed)
```

2023-12-12 05:10 UTC, ReiHashimoto commented on frontend/.env.example
> +
失礼しました、再度実行したところ私の環境でも発生しました。
feのlint errorを解消しました。

2023-12-12 05:19 UTC, ReiHashimoto commented on frontend/.env.example
> +
for-serverではExptConfigでnwb, snakemakeを除外していたところ、mergeでこれらの属性が追加されたのが原因ですね...
これまでのfor-serverのexperiment.yamlにはnwb, snakemakeのフィールドがないところ、そのファイルからExptConfigのインスタンスを生成しようとしてエラーが起きているようです。

私の環境ではexperiment.yamlが残っていない状態だったので発生していませんでした。

今後nwbは必要になることと、下位互換性を踏まえ、初期値としてデフォルトパラメータのインスタンスを生成するようにします。

2023-12-12 05:21 UTC, ReiHashimoto commented on frontend/.env.example
> +
> ※そもそも、起動直後にWorkflow画面が表示されている？（ログイン画面表示となるはず）

.envにIS_STANDALONE=Falseが設定されていない、などでしょうか？

2023-12-12 05:29 UTC, itutu-tienday commented on frontend/.env.example
> +
> .envにIS_STANDALONE=Falseが設定されていない、などでしょうか？

for-serverでは、もともと上記のフラグを持っていなかった様に思います。（multiuser mode固定のため）
設定の仕様を簡潔にする目的で、for-serverでは上記のフラグは不要とするのが適当そうか、と考えますが いかがでしょうか。

2023-12-12 05:35 UTC, ReiHashimoto commented on frontend/.env.example
> +
確かにそうでしたね...
default値の変更で対応します。ありがとうございます。

2023-12-12 06:27 UTC, itutu-tienday commented
@ReiHashimoto 
全体的な確認を行い、動作・仕様面はOK :+1: そうであることを確認しました 

- 動作
  - WEB, Batch … OK
- 仕様
  - barebone issuesの取り込み … 取り込めそうなものは ほぼ取り込み済みと思われる

※全体テスト実施後、Approveを予定

2024-01-11 02:36 UTC, itutu-tienday commented
@ReiHashimoto 
このPRは、現在時点でマージ可能でしたでしょうか？
※直近より develop-main へ改修が入っていく予定のため、基本的に問題なければ、現時点でマージを進めておくのが良いかと思います。

2024-01-11 02:37 UTC, ReiHashimoto commented
@itutu-tienday 
現在RPさんでテスト中で、確認された不具合等の対応をしてくださっているためそれらの改修完了次第merge予定です。

2024-01-11 02:43 UTC, itutu-tienday commented
@ReiHashimoto 
現在テスト中の旨、了解しました。

・直近の修正作業は、一旦 feature/merge-barebone  ブランチからの派生環境で、対応しようと思います。
・また細かな点ですが、以下について対応されていましたらapproveしますので、お伝えください。
  https://github.com/arayabrain/optinist-for-server/pull/245#discussion_r1423424065

2024-01-11 02:56 UTC, ReiHashimoto commented
@itutu-tienday 
> また細かな点ですが、以下について対応されていましたらapproveしますので、お伝えください。

こちらのcommitで対応済みです(be294c2)

2024-01-11 03:40 UTC, itutu-tienday commented on frontend/.env.example
> +
@ReiHashimoto 
> こちらのcommitで対応済みです(https://github.com/arayabrain/optinist-for-server/commit/be294c256530e023aedb689ff6a3a7235a5ea64b)

上記は、nwb, snakemake のパラメータ調整のcommitと思われますが、

> default値の変更で対応します。ありがとうございます。

上記の件（BEの .env で IS_STANDALONE 指定不要とする件）は、まだcommit前でしたでしょうか？

2024-01-11 07:52 UTC, ReiHashimoto commented on frontend/.env.example
> +
@itutu-tienday すみません、push漏れてました...
ca8c177 ですね

2024-01-11 08:39 UTC, itutu-tienday approved these changes

2024-01-22 01:44 UTC, merged