Update experiment API
arayabrain/optinist-for-server pull request #251
Opened 2024-01-18 03:42 UTC by quanpython

2024-01-24 03:38 UTC, itutu-tienday requested changes

2024-01-24 03:38 UTC, itutu-tienday commented on studio/alembic/versions/8f5d1e7d2a25_add_experiment_view_attributes.py
> +"""add experiment view attributes
@quanpython 
I have committed a file similar to this one on the latest develop-main branch, so there is no problem deleting it.
(Please merge develop-main)

2024-01-24 03:38 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +def get_search_db_experiment_query(
In the data registration process of view_attributes, I assume that multibyte characters are escaped (ex: "imaging_depth": "220µm" -> "280\u00b5m"), so I assume that the search string needs to be escaped.
Is escaping at the frontend or the backend the preferred form? (Consultation)

2024-01-24 08:31 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +def get_search_db_experiment_query(
@itutu-tienday I think it should be handled at the frontend (same as #246)

2024-02-02 06:40 UTC, itutu-tienday commented
@quanpython 
Please update this PR with open if status update OK.

2024-02-16 02:02 UTC, itutu-tienday approved these changes

2024-02-16 02:02 UTC, merged