Experiment metadata acquisition UI update
arayabrain/optinist-for-server pull request #253
Opened 2024-01-26 09:36 UTC by sanglevinh

2024-02-02 06:39 UTC, itutu-tienday requested changes

2024-02-02 06:39 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    valueOptions: [1, "â", "a b + ê", 4, 5, 6, 7, 8],
@sanglevinh 
Each item (brain area ...) Is it possible to place a selectbox and a text field filter item together as a provisional arrangement so that the API can be verified to work?

2024-02-02 06:39 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    promoter?: string
@sanglevinh 
In the data display of the data table columns, long text is missing; if you can't see it, use mouse hover to display the text.
*If you have any suggestions for a better UI, please let us know.

2024-02-02 06:39 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@sanglevinh 
First of all, I have a question,
Is it possible to format the json to be displayed in the Edit field of Attributes using frontend?
(Formatted when editing, compressed when sending to API)

If it seems to be relatively simple to handle, I would like to request this PR to handle it as well.
If it seems to require a lot of work, we will create a separate issue.

2024-02-06 04:54 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    valueOptions: [1, "â", "a b + ê", 4, 5, 6, 7, 8],
@itutu-tienday i fixed it, pls check it agian

2024-02-06 04:54 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    promoter?: string
@itutu-tienday i added tooltip, pls check it agian

2024-02-06 04:55 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@itutu-tienday I have added isValid JSON, please check if it is what you mean

2024-02-06 07:30 UTC, itutu-tienday requested changes

2024-02-06 07:30 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    field: "promoter",
@sanglevinh 
In the latest version of the branch (feature/update-exp-api, feature/update_user_interface), the following error seems to occur in the API when filtering on the brain area - image depth item.

>AttributeError: type object 'Experiment' has no attribute 'promoter'

Is it working properly in your environment?

2024-02-06 07:30 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    valueOptions: [1, "â", "a b + ê", 4, 5, 6, 7, 8],
@sanglevinh 
Thank you.
I see that you have modified the list of pull-downs, but would it be possible to address the following, which I mentioned above?

> is it possible to place a selectbox and a text field filter item together as a provisional arrangement

If this is too complicated (or time-consuming), please let me know and I will withdraw the above.

2024-02-06 07:30 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@sanglevinh 
Thank you.
I would like to reiterate the above request, which is as follows Would it be possible to implement?

- current
![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/2b37ca71-c10d-475a-bd1d-acbbdf9544c6)

- expected (Formatted when editing, compressed when sending to API)
![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/bad949c0-bdc8-4803-b5a8-0479e09d1077)

2024-02-06 07:30 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@sanglevinh 
Please change the display of Attributes in DataTable to icon display.

- current
![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/986c7777-8702-4ba3-9124-b369f7a0b173)

- expected
  - Display with the following icon
  - https://mui.com/material-ui/material-icons/?query=text&theme=Outlined&selected=AssignmentOutlined

2024-02-07 04:00 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    valueOptions: [1, "â", "a b + ê", 4, 5, 6, 7, 8],
@itutu-tienday I think about this problem and the JSON problem below, please help me create a clearer task so I can better understand the problem that needs to be solved.

2024-02-07 04:44 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    valueOptions: [1, "â", "a b + ê", 4, 5, 6, 7, 8],
@sanglevinh 
So, again, first a technical question: is it possible to set a pulldown and textbox filter UI for a single column in the current DataTable filter?
→ Currently, all filter operators (is/is not/is any of) are pulldown, but is it possible to add a textbox (Contains, etc.) operator?
→ If the above is too difficult for the DataTable specification, I will withdraw this request.

2024-02-08 05:30 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    field: "promoter",
@sanglevinh 
Can you reproduce the above event?
I would like to confirm this in order to close PR #251 of BE.

2024-02-15 02:12 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    valueOptions: [1, "â", "a b + ê", 4, 5, 6, 7, 8],
@itutu-tienday Do you mean we will use both filter operators: contains and is for the above columns?
If true, this seems unlikely

2024-02-15 02:21 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    field: "promoter",
@itutu-tienday I can still filter normally and see no errors

2024-02-15 02:30 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    valueOptions: [1, "â", "a b + ê", 4, 5, 6, 7, 8],
@sanglevinh 
So, I understand that it is not possible to set different UIs (text, pulldown) for the same column filter. I understand for the moment.

2024-02-15 02:32 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    field: "promoter",
@sanglevinh 
I see... Understood.
Could you please share this with the BE staff?

@quanpython 
Are you aware of the error above? (It seems to be an issue in my environment...)

2024-02-15 03:14 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@itutu-tienday I have formatted it, please check it for me

2024-02-15 03:48 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@itutu-tienday i added icon, pls check it again

2024-02-15 06:29 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    valueOptions: [1, "â", "a b + ê", 4, 5, 6, 7, 8],
@itutu-tienday That's right, using is and contains in the same filter operator is not possible

2024-02-15 06:58 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@sanglevinh 
Thanks. However, I can't seem to confirm the fix in our environment.
Wouldn't `const handleOpenAttributes` be the appropriate fix?

2024-02-15 07:26 UTC, quanpython commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    field: "promoter",
@itutu-tienday 
Looks like you pressed the sort button of `promoter` field while filtering.
Because sorting of these 4 attributes have not been handled on the BE side, it has led to the above error.

2024-02-15 07:35 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@itutu-tienday 

https://github.com/arayabrain/optinist-for-server/assets/109060170/142d63ca-ef79-4804-a01d-701c68b70227

Do you mean reformat like this?
Can you copy it like the video above or do you mean that when you click the 'Save' button to save the value is not saved?
If saving is problematic, it's because there's no API to save the value

2024-02-15 07:57 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    field: "promoter",
@quanpython 
I see.

I assume that support for sorting will be implemented, but is it currently unimplemented?  (Is it not implemented due to technical issues?)

2024-02-15 08:13 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@sanglevinh 
I see that it will be formatted at the time of editing. Thanks.

I guess I didn't communicate it well, but I assume the following behavior.

- When the dialog is initially displayed, the json is formatted and initially displayed.
    - The same for both non-administrator and administrator.
    - Real-time formatting during editing is not necessary.

Also, there is currently no API for updating Attributes, is there? I had forgotten about it.
I will submit a request to add an API in a separate issue.

2024-02-15 08:41 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@itutu-tienday 
- Properties are always visible to admins and non-admins, but only admins have edit permissions.
- I will remove the formatting when editing, only formatting the first time when opening the properties

2024-02-15 09:17 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>    fields: {
@sanglevinh 
It is as expected. Thanks.

2024-02-16 02:00 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +    field: "promoter",
@quanpython 
I confirmed that sorting by view_attributes fileld is working.

As you pointed out, sorting by json filed is assumed to have an impact on performance, but for now, we will use sorting by json filed for the following reasons.

- Consideration of the ease of changing columns in view_attributes
- Data volume (target data is relatively lightweight)

2024-02-16 02:02 UTC, itutu-tienday approved these changes

2024-02-16 02:03 UTC, merged