integrate api options filter
arayabrain/optinist-for-server pull request #257
Opened 2024-02-21 11:02 UTC by sanglevinh

2024-02-22 07:12 UTC, itutu-tienday requested changes

2024-02-22 07:12 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
> +    filterOperators: [
@sanglevinh 
Is it possible to adjust the following behavior when selecting filters?

- Currently
  1. do filter column-1
  2. do filter column-2
     - Before selecting the filter item for column-2, the filter for column-1 is canceled.

- After adjustment
  1. do filter column-1
  2. do filter column-2
     - The filter status of column-1 is retained until the filter item for column-2 is selected.

2024-02-22 07:12 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>  const columns = (
@sanglevinh 

I am considering making the column widths changeable, are there any technical issues I can anticipate if I make them changeable?
If there seems to be no problem, please set the column width to changeable.

- Reference
  - https://mui.com/x/react-data-grid/column-dimensions/#resizing

2024-02-23 09:58 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
>  const columns = (
@itutu-tienday To use resizable, you must use DatagridPro

2024-02-23 10:48 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>  const columns = (
@sanglevinh 
I see. I understand.

2024-02-23 10:56 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +  useEffect(() => {
@sanglevinh 
Just to be sure, please let me know what the modifications are to 712f787.

2024-02-26 02:32 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +  useEffect(() => {
@itutu-tienday Because when changing the filter condition from string to string[], the filter finishes reloading the type even though there is a filter but the filter icon is not displayed, so I modified a bit of the logic so it can run properly.

2024-02-28 05:32 UTC, ReiHashimoto approved these changes
LGTM

2024-02-28 07:22 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>      field: "experiment_id",
@sanglevinh 

Currently, as shown in the following figure, the Experiment ID column display is partially obscured, and I would like to request that you adjust the column width.

- Adjust the column width so that the display is not cut off.
- Pop up the text when the mouse cursor is over the Experiment ID.

![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/62f89812-a368-4daa-b489-b1f35cf047f9)

2024-02-28 09:01 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
>      field: "experiment_id",
@itutu-tienday i changed width, and added tooltip for column experiment id

2024-02-28 09:35 UTC, itutu-tienday approved these changes

2024-02-28 09:35 UTC, merged