Get config filter param API
arayabrain/optinist-for-server pull request #258
Opened 2024-02-22 03:36 UTC by quanpython

2024-02-22 07:26 UTC, itutu-tienday requested changes

2024-02-22 07:26 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +            func.json_extract(
@quanpython 
When multiple filter item values (is any of) are specified from FrontEnd, the number of data acquired seems to be zero. (Is there a problem with the combination of json_extract and IN?)

2024-02-26 07:27 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +            func.json_extract(
@itutu-tienday I used `json_value` instead (f2fe450)

2024-02-26 07:45 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +            func.json_extract(
I have confirmed that it works ok.

2024-02-28 05:57 UTC, itutu-tienday approved these changes

2024-02-28 05:57 UTC, merged