add env metadata edit
arayabrain/optinist-for-server pull request #260
Opened 2024-02-22 06:45 UTC by sanglevinh

2024-02-22 07:48 UTC, itutu-tienday requested changes

2024-02-22 07:48 UTC, itutu-tienday commented on frontend/src/pages/Database/Experiments.tsx
> +const METADATA = process.env.REACT_APP_ENABLE_EXPDB_METADATA_EDITABLE === "true"
@sanglevinh 
Please also maintain the configuration file template (.env.example).

2024-02-22 07:48 UTC, itutu-tienday commented on frontend/src/pages/Database/Experiments.tsx
> +const METADATA = process.env.REACT_APP_ENABLE_EXPDB_METADATA_EDITABLE === "true"
@sanglevinh 
In my environment, even though I set `ENABLE_EXPDB_METADATA_EDITABLE=true` in .env.development, the Attribute Dialog does not seem to reflect the setting.
→ Is this a bug or my setting error?

2024-02-23 02:36 UTC, sanglevinh commented on frontend/src/pages/Database/Experiments.tsx
> +const METADATA = process.env.REACT_APP_ENABLE_EXPDB_METADATA_EDITABLE === "true"
@itutu-tienday 
you should set REACT_APP_ENABLE_EXPDB_METADATA_EDITABLE = true

2024-02-23 02:37 UTC, sanglevinh commented on frontend/src/pages/Database/Experiments.tsx
> +const METADATA = process.env.REACT_APP_ENABLE_EXPDB_METADATA_EDITABLE === "true"
@itutu-tienday i added it, pls check it again

2024-02-23 02:54 UTC, itutu-tienday commented on frontend/src/pages/Database/Experiments.tsx
> +      <DatabaseExperiments
@sanglevinh 
If you are an administrative user and REACT_APP_ENABLE_EXPDB_METADATA_EDITABLE = false, not only hide the Save button, but also make the textarea readonly.

2024-02-23 03:18 UTC, sanglevinh commented on frontend/src/pages/Database/Experiments.tsx
> +      <DatabaseExperiments
@itutu-tienday i fixed it, pls check it again

2024-02-23 10:40 UTC, itutu-tienday requested changes

2024-02-23 10:40 UTC, itutu-tienday commented on frontend/src/pages/Database/Experiments.tsx
> +      <DatabaseExperiments
@sanglevinh 
I have checked the modifications, OK.

2024-02-23 10:40 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +          {role && !readonly && (
@sanglevinh 
Please let me know when the metadata update API call is added.
- #259

2024-02-26 02:29 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +          {role && !readonly && (
@itutu-tienday I have a small question, why do I use both the REACT_APP_ENABLE_EXPDB_METADATA_EDITABLE variable and the API call to check?

2024-02-26 02:43 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +          {role && !readonly && (
@sanglevinh 
My instructions seemed a bit confusing, so I separated them into the following issues.

- #305

I hope the above has conveyed my intention.
If OK, I will close this thread.

2024-02-26 02:53 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +          {role && !readonly && (
@itutu-tienday 
What I'm understanding is that the API call of #305, and the REACT_APP_ENABLE_EXPDB_METADATA_EDITABLE variable both have the purpose of checking display metadata.
If so, I think I should only use one of the two
Or can you explain to me why we have to use both to check metadata display?

2024-02-26 03:19 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +          {role && !readonly && (
@itutu-tienday yes i will integrate API #305

2024-02-28 06:28 UTC, itutu-tienday approved these changes

2024-02-28 06:29 UTC, merged