preprocessing
arayabrain/optinist-for-server pull request #262
Opened 2024-02-28 01:37 UTC by ReiHashimoto

Tasks
- [x] 顕微鏡入力ノードの作成
- [ ] preprocessing
  - [x] stack_average
  - [ ] stack_phase_correct
  - [ ] stack_register
  - [ ] script_get_orimap (未提供)
  - [ ] CNMF (未提供)
- [ ] NWBへの保存処理
- [ ] バッチ処理
- [ ] 顕微鏡入力ノードをデータセットから選択する方式へ改修

構成図
- https://drive.google.com/file/d/1-Zt4qCipZJLLKX_NkQFRBtFxoqzJMLQu/view?usp=drive_link

## 仕様等
- 一連の処理の動作確認のため、まずはworkflow画面で実行可能なノードとして組み込み
  - 顕微鏡は.oir, .nd2, .tifなどに混合の1ノードで実装
  - microscope→preprocessingで結合可能な形で一旦実装している
    ![Screenshot 2024-02-28 at 10 35 46](https://github.com/arayabrain/optinist-for-server/assets/42664619/84413570-6a0b-457d-8701-4cec1445a28e)

2024-02-28 07:44 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/FileSelect.tsx
> +      return ".nd2,.oir,.isxd,.tif,.tiff,.xml"
現時点では仮実装かと思いますが、thorlabsのデータ形式は、zip形式の想定となります。

※なお単なる .zip の拡張子だと、不正なデータアップロードを弾きづらいかもしれないため、例えば ".thor.zip" のように拡張子を拡張する形が良いかもしれません。（備忘）

2024-02-28 08:32 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/conda/expdb.yaml
> +  - gcc==12.1.0
一応の確認ですが、expdb の env は gcc の依存がありますでしょうか

2024-02-28 08:32 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/stack_register.py
> +    Extended to n-dimension by Kenichi Ohki  2011.7.8.
細かいですが、MATLABコード（*.m）からの移植である旨の補足（移植元ファイル名）があっても、良いかもしれません

2024-02-28 08:47 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/conda/expdb.yaml
> +  - gcc==12.1.0
なおこちらの環境では、workflowのRUN時に以下のエラー（preprocessing node）が確認されました

> 〜 gcc 12.1.0 is not installable because it requires 〜

2024-02-28 09:02 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/expdb/conda/expdb.yaml
> +  - gcc==12.1.0
@itutu-tienday 
workflowのconda環境上で顕微鏡ノードのctypesを実行する際に以下のエラーが発生していたため、その対応として入れたものです。
```
GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libicuuc.so.72)
```

docker imageに対して
```
apt-get install libstdc++6
```
などを事前に実行しておいてもsnakemakeのcondaから参照されず、結局この方法で解消したという次第です。

以下の情報などを参考にしたのですが、dockerでもOS差があるかもしれませんね...
- https://qiita.com/dekavit/items/a6a62044d91a05feccc8
- https://stackoverflow.com/questions/72540359/glibcxx-3-4-30-not-found-for-librosa-in-conda-virtual-environment-after-tryin

2024-02-28 09:42 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/conda/expdb.yaml
> +  - gcc==12.1.0
@ReiHashimoto 
なるほど、snakemake上での実行に問題があるということですね。
ちょっとこちらでも確認しておこうと思います。

> workflowのconda環境上で

ちなみに上記の環境は、docker-compose*.yaml の構築環境上でしょうか？
またMac環境ではいかがでしょうか

2024-02-28 10:15 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/expdb/conda/expdb.yaml
> +  - gcc==12.1.0
@itutu-tienday 
docker-compose.dev.yamlの環境で実行しています。

Mac上ではResolvePackageNotFoundになってしまいますね。

```
conda search conda-forge::gcc
```
でチャンネル指定もした上で探してみましたが、`No match found for: conda-forge::gcc.`でした。

2024-02-28 10:45 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/conda/expdb.yaml
> +  - gcc==12.1.0
あ、Mac環境は dll (nikon, olympus) はサポート外でしたね。
Mac以外の各環境にて、gccの指定不要でsnakemake実行可能か、検証します。

2024-02-29 03:13 UTC, itutu-tienday commented
以下の件（顕微鏡モジュールの共有ライブラリの参照不具合）について、調査情報を記載
- https://github.com/arayabrain/optinist-for-server/pull/262#discussion_r1505594017

----

#### 事象
- docker host 上（UbuntuやWindows）や docker container内では、顕微鏡モジュールは正常動作するが、「docker container + conda env」上で動作させると、共有ライブラリの参照エラーが発生している。
- ＜詳細＞
  - 現在の対象はolympusのみ（nikon, isx, thorlabs は動作OK）
  - エラーログ
  	> OSError: /app/.snakemake/conda/\*/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /lib/x86_64-linux-gnu/libicuuc.so.72)

#### 原因
- docker container上の /lib/\*/.so と、conda env上の /lib/\*/.so が相互参照するケースがあり、ここでdockerとcondaの lib にバージョン差異があることにより、参照エラーが発生。
  - ＜現在時点のlibバージョン差異＞
  	- docker … libstdc++.so.6.0.30
  	- conda … libstdc++.so.6.0.29

#### 対策
- 案1) docker or conda の libstdc++.so バージョンを揃える
  - → `conda install gcc` や `conda install libgcc` を検証したところ、「うまくインストールできない」「期待するバージョンをインストールできない」という問題を確認。
  - なおいずれ conda の libstdc++.so のバージョンが上がり、自動的に問題解消されることも想定される。
- 案2) conda env 内の /lib 配下に、docker container の /lib/\*/.so へのシンボリックリンクを張る
  - → この方法では動作OKは確認されたが、運用面で課題がある（自動化が難しい可能性）
- 案3) 共有ライブラリ（ctypes）を利用するコードは、conda env に依存しないように、呼び出しコード側で対処
  - → 検討中

2024-02-29 03:14 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/conda/expdb.yaml
> +  - gcc==12.1.0
Memo: 以下に調査レポートを記載
- https://github.com/arayabrain/optinist-for-server/pull/262#issuecomment-1970320236

2024-03-19 01:44 UTC, itutu-tienday requested changes
- 各PreProcessing関連関数について、大きめの入力データを用いた、性能確認と必要な改善適用 が、要事前実施かと思います。

2024-03-19 01:44 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/stack_average.py
> +def stack_average(stack: np.ndarray, period, runs=None):
stack_average は、ScriptGetOrimap の対応時に更新済みのため（主に性能改善）、アップデートをお願いします。

2024-03-19 01:44 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/stack_register.py
> +    result_stack = stack.copy()
この stack の copy は、メモリを大きく消費はしないでしょうか？ （数GBの stack の入力は想定されないか？）
→ もしメモリ消費量が大きい場合、stack を mutable としてメモリ消費を押される方法など、想定できるかと思われます。（ロジック上問題ないかは要チェック）
→ またメモリ消費量が限定的であれば（プロセス全体で stack の最大2倍まで、など）、シンプルにstackはcopyで統一、でもよさそうかと考えます。

2024-03-19 01:46 UTC, itutu-tienday requested changes

2024-03-19 01:46 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/stack_register.py
> +    out = np.zeros(stack.shape)
以下に同様
https://github.com/arayabrain/optinist-for-server/pull/262/files#r1529561281

2024-03-19 01:46 UTC, itutu-tienday commented on studio/app/optinist/wrappers/expdb/stack_register.py
> +    outstack = np.zeros(stack_dim)
以下に同様
https://github.com/arayabrain/optinist-for-server/pull/262/files#r1529561281

2024-03-21 12:08 UTC, itutu-tienday requested changes

2024-03-25 00:11 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/expdb/get_orimap.py
> +    # 標準偏差が1の1次元ガウシアンフィルター
10ec345 コメントを修正しました

2024-03-25 00:11 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/expdb/stack_register.py
> +    Extended to n-dimension by Kenichi Ohki  2011.7.8.
10ec345 コメントを修正しました

2024-03-25 00:15 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/expdb/stack_average.py
> +def stack_average(stack: np.ndarray, period, runs=None):
c1eaa6c 性能改善を行いました。4GB程度のファイル(ori004.nd2)で動作確認済です。

2024-03-25 00:16 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/expdb/stack_register.py
> +    result_stack = stack.copy()
c1eaa6c 性能改善を行いました。変数を分けずに上書きする方針で対応しています。

2024-03-25 00:18 UTC, ReiHashimoto commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/FileSelect.tsx
> +      return ".nd2,.oir,.isxd,.tif,.tiff,.xml"
c37159e e824bea thorlabsのデータ形式を.thor.zipに変更しました。

2024-03-25 00:18 UTC, ReiHashimoto commented on studio/app/const.py
> +ACCEPT_MICROSCOPE_EXT = [".nd2", ".oir", ".isxd", ".tif", ".tiff", ".xml"]
https://github.com/arayabrain/optinist-for-server/pull/262#discussion_r1536946879
こちらのコメント同様です。

2024-03-25 01:19 UTC, ReiHashimoto commented
@itutu-tienday 
preprocessing→caimanの動作検証にあたり、以下の準備をお願いします。

- nd2ファイルの配置
  - https://drive.google.com/drive/folders/1an6Pvtqasc_OyGgy3FtaDEQtMUQC_Qr8?usp=drive_link
  - `OF_PRC_001.nd2`はM000044のsubjectのデータのため、データセットディレクトリの`M000044/M000044_OF-PRC-001/M000044_OF-PRC-001.nd2`となるように配置してください。
    - その他cellmask, tc, tsのmatファイル、metadataのjsonファイルも同ディレクトリにある想定です。未配置の場合はこちらを使ってください。
      - https://drive.google.com/file/d/1PB_fVzWd3S9_eRsjDdXWZLGdwz_uGLPQ/view?usp=drive_link
- バッチ処理の実行(DBにM000044_OF-PRC-001が未登録の場合)
  - `M000044/M000044_OF-PRC-001.proc`ファイルを作成して一度バッチを実行し、DBにデータ登録をお願いします。

2024-03-25 01:47 UTC, ReiHashimoto commented
@itutu-tienday 
064220d 取り急ぎこちらのコミットでcaimanが使用可能な状態になりました。
- 入力: microscopeノード→M000044_OF-PRC-001のレコードを選択
- アルゴリズム：preprocessing → caiman_cnmfを連結

ただし、こちらの環境での検証では、caimanが途中でSigKillされてしまいました。
おそらくメモリ不足ですが、dockerに16GBまで使用許可しても同様でした。

解析対象のファイル(preprocessingの出力のstack)は1.34GB程度のtifファイルなので、原因調査中です。

2024-03-26 02:25 UTC, itutu-tienday requested changes

2024-03-26 02:25 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_runner.py
> +            # expdb_batch.cell_detection_cnmf()
直近リリース時に、cnmf処理をスキップさせる形でのリリースとすることが想定されるが、
その場合、既存の中間成果物（ユーザーにより手動アップロードされているもの。TCファイルなど）を、ファイルクリーニング処理から除外する必要がある。
→ 必要な中間成果物が削除されている場合、後続処理でエラーが生じるため。

2024-03-26 02:25 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_unit.py
> +    @stopwatch(callback=__stopwatch_callback)
preprocess は処理時間を要するため、進捗ログ出力をもう少し追加しても良いと考えられる。
→ 一旦こちらで幾つか追加してみます。

2024-03-26 02:46 UTC, itutu-tienday commented on studio/app/optinist/dataclass/microscope.py
> +    def data(self):
このプロパティは、アクセスするたびにRawデータのloadが実行されていますが、
Image Rawデータのloadは重い（メモリ,CPU）処理のため、少し考慮を入れておけると良さそうです。

- 対応案
  1. loadされたデータは明確に破棄(clearメソッドなどで)されるまでは、インスタンス内に保持する（≒singleton）
  2. property ではなく、処理内容が明確な名称・メソッドにしておく（load_data() など）

2024-03-26 03:20 UTC, itutu-tienday commented on studio/app/optinist/core/expdb/batch_unit.py
> +    @stopwatch(callback=__stopwatch_callback)
以下で幾つかloggingを追加
- b7454a7d1a84efb965089bad842b0b7af3303306

ただし、処理モジュール側（wrapper module）でのloggingがより適切。
→ optinist側でのlogging処理の整備を必要とするため、別途対応となる。

2024-03-26 05:57 UTC, itutu-tienday commented on studio/app/optinist/wrappers/caiman/cnmf.py
>  def caiman_cnmf(
caiman wrapper へ、以下 barebone での対応の取り込みが必要かと想定される。
- https://github.com/arayabrain/barebone-studio/issues/176

2024-03-26 06:14 UTC, itutu-tienday commented
@ReiHashimoto 
- https://github.com/arayabrain/optinist-for-server/pull/262#issuecomment-2017066797
> ただし、こちらの環境での検証では、caimanが途中でSigKillされてしまいました。
> おそらくメモリ不足ですが、dockerに16GBまで使用許可しても同様でした。

こちらの環境（Ubuntu 22, Mem 32GB(空き12GB程度)）でも、同様に SIGKILL: 9 でクラッシュしているようです。

上記につき、現在手持ちのデータで開発環境での動作確認が行えない状況のため、ユーザーへ軽量データ提供を改めて依頼しようと思います。
※別途メモリ削減可否の検証は要

2024-03-26 15:31 UTC, ReiHashimoto commented on studio/app/optinist/core/expdb/batch_runner.py
> +            # expdb_batch.cell_detection_cnmf()
> 既存の中間成果物（ユーザーにより手動アップロードされているもの。TCファイルなど）を、ファイルクリーニング処理から除外する必要がある。

これらはoutputsの1階層上のため、削除されない認識です。

```
EXPDB_DIR
  └ SUBJECT_ID
         └ EXPERIMENT_ID
                ├ timecourse.mat
                ├ trialstructure.mat
                ├ metadata.json
                ├

2024-03-26 15:40 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/caiman/cnmf.py
>  def caiman_cnmf(
対応しました。
一部パラメータはバッチでそのまま使用されるように提供MATLABコードのデフォルトパラメータに寄せています。
(特にK=2000がデフォルトなので、検証時には下げるなど対応が必要)

2024-03-28 02:23 UTC, itutu-tienday commented on studio/app/optinist/core/nwb/lab_metadata.py
> +ns_path = f"{name}.namespace.yaml"
現在、NWBの構成ファイル `*.(namespace|extensions).yaml` はソースツリーの直下に出力されているようですが、直下ではなく studio/ の配下に出力する形が適切かと思われます。
※ studio/app/ 配下に出力されているケースなどもある？ （アプリケーション実行時の current directory パスに出力先が依存している？）

2024-03-28 03:01 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/ExpDbNode.tsx
> +export const ExpDbSelectDialog = memo(function ExpDbSelectDialog({
barebone-studio で組み込まれている以下の機能を、for-serverにも移植しておくとよいと思われます。

- ノードの設定・構成を変更した場合、変更対象ノードがハイライトされる
- また input node（for-serverでは、microscope）を変更した場合は、RUNは不可（RUN ALLのみ）とする
  - 実際に for-server で 「preprocessed_data変更 → 再度RUN」を実行した場合、後続ノードがエラーとなったため、RUN ALL必須でよいものと思われる

2024-03-28 03:19 UTC, itutu-tienday approved these changes

2024-03-28 07:53 UTC, merged

2024-04-01 03:25 UTC, ReiHashimoto commented on studio/app/optinist/dataclass/microscope.py
> +    def data(self):
こちらについては、readerとdataプロパティを分ける形で対応済です。

2024-04-01 04:57 UTC, ReiHashimoto commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/ExpDbNode.tsx
> +export const ExpDbSelectDialog = memo(function ExpDbSelectDialog({
> また input node（for-serverでは、microscope）を変更した場合は、RUNは不可（RUN ALLのみ）とする

について、以下のPRで対応しました。
- #283 

なお、
> ノードの設定・構成を変更した場合、変更対象ノードがハイライトされる

については既に適用されている認識なのですが、反映されないパターンがあれば詳細をいただけますと幸いです。

2024-04-01 05:58 UTC, itutu-tienday commented on frontend/src/components/Workspace/FlowChart/FlowChartNode/ExpDbNode.tsx
> +export const ExpDbSelectDialog = memo(function ExpDbSelectDialog({
修正確認しました。

> ノードの設定・構成を変更した場合、変更対象ノードがハイライトされる

上記は、新規Workflow(まだIDがないもの)は、設定変更時はハイライト対象外ですね。
既存Workflowについては、変更点のハイライトは機能していますので、問題ないかと思います。

2024-04-01 09:36 UTC, itutu-tienday commented on studio/app/optinist/dataclass/microscope.py
> +    def data(self):
@ReiHashimoto 
以下の PR で少し調整を行っています。
レビューをお願いできればと思います。
- https://github.com/arayabrain/optinist-for-server/pull/285

2024-04-08 02:25 UTC, itutu-tienday commented on studio/app/optinist/core/nwb/lab_metadata.py
> +ns_path = f"{name}.namespace.yaml"
（メモ）
以下での後続対応とする。ここではクローズ
https://github.com/arayabrain/barebone-studio/issues/330