Feature/Database API
arayabrain/optinist-for-server pull request #42
Opened 2023-07-07 09:08 UTC by quanpython

2023-07-12 06:13 UTC, ReiHashimoto requested changes
For now, update to use fastapi-pagination.
See the comment for detail.

Please wait fot the task for another comment (file move) until we decide name.

2023-07-12 06:13 UTC, ReiHashimoto commented on studio/app/common/routers/database.py
Excuse me for not explaining differences between app/common and app/optinist.
app/common -> (almost) not domain specific files
app/optinist -> neuro science domain specific files

In this context, database cell and experiment are a kind of brain data.
So, we'd like to put these files into app/optinist.

And filename "database" may be confusing because we plan to use RDB.
Please wait till we decide names.

@itutu-tienday 
用語について、先日の打ち合わせでも感じたのですがRDBが入ってくる以上「データベース」は紛らわしい気がします。
APIのパスとしては今のままでも良いと思うのですが、スキーマのクラス名やファイル名、呼称としては別なものを用意した方が誘うです。
brain datasetなどいかがでしょうか？
この場合、スキーマとして
BrainDatasetsにBrainCell, BrainExperimentが含まれるイメージです。

2023-07-13 09:05 UTC, ReiHashimoto commented on studio/app/common/routers/database.py
@quanpython 

As api schema updated, please apply following changes.

- rename routers/database.py to routers/expdb.py
- schemas/database to schemas/expdb
- change class prefix Db to ExpDb
  - See details shared in this file(optinist-server-apidoc-v0.1.4.html).

2023-07-14 02:50 UTC, quanpython commented on studio/app/common/schemas/base.py
> +    total_pages: Optional[int] = 0
@ReiHashimoto  With `fastapi-pagination`, do you want the JSON response like this?
```
{
  "items": [
    {
      "id": 0,
      "experiment_id": "string",
      "attributes": {},
      "share_type": 0,
      "fields":{},
      "cell_image_urls": [],
      "graph_urls": [],
      "publish_status": 0,
      "created_time": "2023-07-13T17:40:29.925Z",
      "updated_time": "2023-07-13T17:40:29.925Z"
    }
  ],
  "total": 0,
  "limit": 0,
  "offset": 0,
  "header": {
    "brain_area": "string",
    "cre_driver": "string",
    "reporter_line": "string",
    "imaging_depth": 0
  }
}
```

2023-07-14 03:07 UTC, ReiHashimoto commented on studio/app/common/schemas/base.py
> +    total_pages: Optional[int] = 0
@quanpython 
Yes, the response's pagination schema would be different from provided in `optinist-server-apidoc-v0.1.4.html`, it's OK.

2023-07-18 04:46 UTC, itutu-tienday approved these changes

2023-07-18 05:13 UTC, ReiHashimoto approved these changes
LGTM

2023-07-18 05:32 UTC, merged