Feature/database experiments
arayabrain/optinist-for-server pull request #50
Opened 2023-07-11 03:09 UTC by sanglevinh

2023-07-12 04:57 UTC, ReiHashimoto requested changes

2023-07-12 04:57 UTC, ReiHashimoto commented on studio/__main_unit__.py
> +    return await root(request)
Sorry, I couldn't understand what this route for.
Could you explain?

2023-07-12 04:57 UTC, ReiHashimoto commented on frontend/src/components/DatabasePublic.tsx
I'd appreciate it if you'd move this page to `frontend/src/pages/DatabasePublic/index.tsx`.

We refactored to put components with route defined in App.tsx into `frontend/src/pages`.

And put related components (in this case, DatabaseExperiments.tsx) into `frontend/src/components/{Page}`(in this case, `frontend/src/components/DatabasePublic/DatabaseExperiments.tsx`).

2023-07-12 04:57 UTC, ReiHashimoto commented on frontend/src/components/DatabaseExperiments.tsx
> +}
CC: @reactplus-thom 

Maybe MuiDataGrid is better, because we want to add data filter in the future.
MuiDataGrid has more features to sort and filter data in default.

In that case, 'Infinite scroll' maybe difficult bacause it's a pro plan feature. 
https://v5.mui.com/x/react-data-grid/row-updates/#infinite-loading
But I don't think 'Infinite scroll' is must requirement...

@itutu-tienday 
個人的にはDataGridを使用した方が、ソートやフィルタの実装も楽で良いと思っています。
ただし、無限スクロールはDataGridのProプランの機能になってしまうので実装が難しいという懸念もありますが、個人的にはそもそも無限スクロールは要望として上がっていない認識です。
方針としていかがでしょう？

2023-07-13 04:14 UTC, sanglevinh commented on studio/__main_unit__.py
> +    return await root(request)
@ReiHashimoto 
It is used to fix 404 error when reloading page other than "/".

2023-07-13 04:21 UTC, sanglevinh commented on frontend/src/components/DatabasePublic.tsx
@ReiHashimoto
I changed the path to "frontend/src/components/DatabaseExperiments.tsx" because I want to reuse it in private mode.

2023-07-13 04:30 UTC, sanglevinh commented on frontend/src/components/DatabaseExperiments.tsx
> +}
@ReiHashimoto 
Thanks, I will implement it.

2023-07-13 04:36 UTC, ReiHashimoto commented on frontend/src/components/DatabaseExperiments.tsx
> +}
@sanglevinh 

Sorry, it's still just my opinion.
Could you wait for implementation?
(Plan to dIscuss in today's meeting.)

2023-07-13 04:38 UTC, ReiHashimoto commented on frontend/src/components/DatabasePublic.tsx
Ah, that's make sense.
Really good solution! Thank you.

2023-07-13 04:48 UTC, ReiHashimoto commented on studio/__main_unit__.py
> +    return await root(request)
@sanglevinh 

OK, that sounds needed.

Could you separate this change into another PR?
I want apply this change to fork origin repo.
(Database tables are specific for this product, but this routing is useful for both.)

And more, I want apply same thing to frontend source.
That is, in App.tsx, add <Route path="*", ...> at the end of the Routes.
Action is redirect to "/" is enough, I think.

Could you make another PR for these?

2023-07-13 07:42 UTC, ReiHashimoto commented on frontend/src/components/DatabaseExperiments.tsx
> +}
@sanglevinh CC: @reactplus-thom 
Thank you for taking the time for meeting!

Please try using material ui's [DataGrid](https://v5.mui.com/x/react-data-grid/) component.
And you don't have to implement infinite loading, just implement normal pagination is enough.

We assume data rows passed to DataGrid will exceed 10,000.
So, use pagination with serverside like following.
https://v5.mui.com/x/react-data-grid/pagination/#server-side-pagination

If difficulty in using DataGrid, using [Table Component](https://mui.com/material-ui/react-table/) is OK.

2023-07-14 09:32 UTC, ReiHashimoto commented on frontend/src/components/DatabaseExperiments.tsx
> +}
Thank you for implementing this!

2023-07-18 07:09 UTC, ReiHashimoto commented on studio/__main_unit__.py
> +    return await root(request)
I've removed this.
Backend API server should return 404 with unknown path.
I've added frontend redirect on #61 instead.

2023-07-18 07:09 UTC, ReiHashimoto approved these changes

2023-07-18 07:53 UTC, itutu-tienday commented
@sanglevinh 
Please resolve the conflict.

2023-07-18 10:45 UTC, sanglevinh commented
> 
@ReiHashimoto 
I solved it.

2023-07-18 10:46 UTC, sanglevinh commented
> @sanglevinh Please resolve the conflict.
@ReiHashimoto
I solved it.

2023-07-18 11:34 UTC, merged