Feature/database
arayabrain/optinist-for-server pull request #52
Opened 2023-07-12 11:49 UTC by quanpython

2023-07-13 08:29 UTC, itutu-tienday reviewed
add some review comment

2023-07-13 08:29 UTC, itutu-tienday commented on docker-compose.dev.yml
> +    environment:
Connection information to the DB should be set in the .env file (studio/config/.env)

2023-07-13 08:29 UTC, itutu-tienday commented on docker-compose.dev.yml
> +    image: mariadb:10.3
mariadb assumes a version that is compatible with mysql8.
(probably mariadb 10.4 or later)

*If you have any concerns, please let us know.

2023-07-13 08:57 UTC, ReiHashimoto commented on studio/app/common/models/cell.py
Like #42 , we want to separate models by domain.

In this case, 

- app/common/models
  - base
  - user
  - workspace
- app/optinist/models
  - cell
  - experiment

Could you apply?

2023-07-14 00:00 UTC, ReiHashimoto commented on docker-compose.dev.yml
> +      - PMA_PASSWORD=docker
Is it possible to define these environments in studio/config/.env as db?

2023-07-14 00:42 UTC, ReiHashimoto requested changes

2023-07-14 00:42 UTC, ReiHashimoto commented on docker-compose.dev.yml
I think running migration required on container start.

e.g.) add `RUN alembic upgrade head` to Dockerfiles
Any better solution is welcome.

2023-07-14 01:02 UTC, ReiHashimoto commented on studio/app/common/models/cell.py
Thank you for your applying!

2023-07-14 04:09 UTC, ReiHashimoto commented on docker-compose.dev.yml
> +      - PMA_PASSWORD=docker
Resolved, thank you.

2023-07-14 05:13 UTC, ReiHashimoto requested changes

2023-07-14 08:56 UTC, ReiHashimoto commented on alembic.ini
> +sqlalchemy.url = mysql+pymysql://docker:docker@db/docker
Solved, Thank you.

2023-07-14 11:07 UTC, quanpython commented on docker-compose.dev.yml
alembic is already in pyproject.toml.
Have you try again with `docker-compose -f docker-compose.dev.yml up --build`?

2023-07-18 05:18 UTC, ReiHashimoto commented
@quanpython cc: @itutu-tienday 

dev container is OK.

But prod container still fails with following errors.
Can you reproduce this?

```
docker compose up --build
 => ERROR [studio 8/8] RUN alembic upgrade head                                                                                                                    2.4s
------
 > [studio 8/8] RUN alembic upgrade head:
2.269 Traceback (most recent call last):
2.269   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 613, in connect
2.269     sock = socket.create_connection(
2.269   File "/usr/local/lib/python3.8/socket.py", line 787, in create_connection
2.269     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
2.269   File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
2.269     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
2.269 socket.gaierror: [Errno -2] Name or service not known
2.269 
2.269 During handling of the above exception, another exception occurred:
2.269 
2.269 Traceback (most recent call last):
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
2.269     return fn()
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 320, in connect
2.269     return _ConnectionFairy._checkout(self)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 884, in _checkout
2.269     fairy = _ConnectionRecord.checkout(pool)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 486, in checkout
2.269     rec = pool._do_get()
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
2.269     return self._create_connection()
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 266, in _create_connection
2.269     return _ConnectionRecord(self)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 381, in __init__
2.269     self.__connect()
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 678, in __connect
2.269     pool.logger.debug("Error on connect(): %s", e)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2.269     compat.raise_(
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2.269     raise exception
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 673, in __connect
2.269     self.dbapi_connection = connection = pool._invoke_creator(self)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 578, in connect
2.269     return dialect.connect(*cargs, **cparams)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
2.269     return self.dbapi.connect(*cargs, **cparams)
2.269   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
2.269     self.connect()
2.269   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 664, in connect
2.269     raise exc
2.269 pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'db' ([Errno -2] Name or service not known)")
2.269 
2.269 The above exception was the direct cause of the following exception:
2.269 
2.269 Traceback (most recent call last):
2.269   File "/usr/local/bin/alembic", line 8, in <module>
2.269     sys.exit(main())
2.269   File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 590, in main
2.269     CommandLine(prog=prog).main(argv=argv)
2.269   File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 584, in main
2.269     self.run_cmd(cfg, options)
2.269   File "/usr/local/lib/python3.8/site-packages/alembic/config.py", line 561, in run_cmd
2.269     fn(
2.269   File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 378, in upgrade
2.269     script.run_env()
2.269   File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 569, in run_env
2.269     util.load_python_file(self.dir, "env.py")
2.269   File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
2.269     module = load_module_py(module_id, path)
2.269   File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
2.269     spec.loader.exec_module(module)  # type: ignore
2.269   File "<frozen importlib._bootstrap_external>", line 843, in exec_module
2.269   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2.269   File "studio/alembic/env.py", line 82, in <module>
2.269     run_migrations_online()
2.269   File "studio/alembic/env.py", line 72, in run_migrations_online
2.269     with connectable.connect() as connection:
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
2.269     return self._connection_cls(self, close_with_result=close_with_result)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
2.269     else engine.raw_connection()
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
2.269     return self._wrap_pool_connect(self.pool.connect, _connection)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
2.269     Connection._handle_dbapi_exception_noconnection(
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
2.269     util.raise_(
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2.269     raise exception
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
2.269     return fn()
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 320, in connect
2.269     return _ConnectionFairy._checkout(self)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 884, in _checkout
2.269     fairy = _ConnectionRecord.checkout(pool)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 486, in checkout
2.269     rec = pool._do_get()
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
2.269     return self._create_connection()
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 266, in _create_connection
2.269     return _ConnectionRecord(self)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 381, in __init__
2.269     self.__connect()
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 678, in __connect
2.269     pool.logger.debug("Error on connect(): %s", e)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
2.269     compat.raise_(
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2.269     raise exception
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 673, in __connect
2.269     self.dbapi_connection = connection = pool._invoke_creator(self)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 578, in connect
2.269     return dialect.connect(*cargs, **cparams)
2.269   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
2.269     return self.dbapi.connect(*cargs, **cparams)
2.269   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 353, in __init__
2.269     self.connect()
2.269   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 664, in connect
2.269     ra [...]

2023-07-18 06:08 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +            common_model.Organization.id == optinist_model.Experiment.organization_id,
users.organizasion_id and also requires a join, do you have any discrepancies in perception?

2023-07-18 06:08 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +    db.add(exp)
- "Data publish" is updating experiments.publish_status, not adding records, but are you creating a new experiments in the following?
- There are multiple data parameters, and for the experiments_share_users table, the operation is to replace all existing data (delete all -> register all).

2023-07-18 06:45 UTC, ReiHashimoto commented on studio/app/optinist/routers/expdb.py
> +    sortOptions: SortOptions = Depends(),
@quanpython 
we are no longer need to use self defined limit and offset (Defined in `SortOptions`) bacause  you've added fastapi-pagination.

use LimitOffsetPage as response_model, and just add sort as query parameter is enough.
https://uriyyo-fastapi-pagination.netlify.app/tutorials/limit-offset-pagination/

2023-07-18 06:55 UTC, quanpython commented
> @quanpython cc: @itutu-tienday
> 
> dev container is OK.
> 
> But prod container still fails with following errors. Can you reproduce this?

@ReiHashimoto 
Because when run `alembic upgrade head`, database container haven't started yet.
It is solved by moving `alembic upgrade head` command to `docker-compose.yml` 5dcaf13621687ab10f04e3877bd10318e5e31229
Thank you.

2023-07-18 07:05 UTC, ReiHashimoto commented
@quanpython 
prod container's problem has been resolved, thank you!

2023-07-18 07:09 UTC, itutu-tienday commented on docker-compose.dev.yml
> +      - "3306:3306"
Set here as "23306:3306"

2023-07-18 07:09 UTC, itutu-tienday commented on docker-compose.yml
> +      - "3306:3306"
Set here as "23306:3306"

2023-07-18 07:11 UTC, itutu-tienday commented on studio/config/.env.example
> +DATABASE_URL=mysql+pymysql://docker:docker@db/docker
Some of the data in DATABASE_URL and MYSQL_* are duplicated, is it possible to manage them smartly in one place?

2023-07-18 08:58 UTC, itutu-tienday approved these changes

2023-07-18 08:59 UTC, itutu-tienday commented on docker-compose.dev.yml
> +      - "3306:3306"
I withdraw the above once

2023-07-18 08:59 UTC, itutu-tienday commented on docker-compose.yml
> +      - "3306:3306"
I withdraw the above once

2023-07-18 09:01 UTC, itutu-tienday approved these changes

2023-07-18 09:05 UTC, ReiHashimoto approved these changes
Still required changes exists, approve for now.

2023-07-18 11:33 UTC, merged

2023-07-19 02:12 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +    sortOptions: SortOptions = Depends(),
I already remove self defined limit and offset

2023-07-19 02:14 UTC, quanpython commented on studio/config/.env.example
> +DATABASE_URL=mysql+pymysql://docker:docker@db/docker
Yes. Just use MYSQL_* is enough because DATABASE_URL is generate from `assemble_db_connection` function in `studio/app/common/db/config.py`

2023-07-19 02:16 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +    db.add(exp)
`exp` is an existing experiment object from the database. So  `db.add(exp)` line adds the modified experiment to the database session to update it rather than create a new one.
To avoid misunderstandings, if the experiment object is already associated with the database session, it is better to omit the `db.add(exp)` line.
Thank you.