add tc, ts and matlab input nodes
arayabrain/optinist-for-server pull request #54
Opened 2023-07-14 01:39 UTC by ReiHashimoto

- resolves #4 
- resolves #38 

Matlabファイル, tc, tsファイルのノードを追加
いずれも.mat拡張子のファイルをアップロード、選択可能

![Screenshot 2023-07-14 at 10 23 22](https://github.com/arayabrain/optinist-for-server/assets/42664619/8e147e4c-b0aa-4af6-bbb9-c43d5b4edc23)

汎用的にmatlabファイルを読み込むため、InputNodeのパラメータとして以下を用意

- fieldName
  - Matlab構造体でデータを保持しているフィールド名を指定
- index
  - ndarrayにアクセスするために、追加のindex指定が必要な場合に使用する
  - 配列で指定(0, 0など)
    - テキストフィールドになっており、無効な値の場合はundefinedに戻す

これらのパラメータはファイルの選択後に表示されるsettingsボタンから設定可能
![Screenshot 2023-07-14 at 10 25 12](https://github.com/arayabrain/optinist-for-server/assets/42664619/aa3c3588-c9a5-4a01-b54a-accaaebd086f)

ただし、TC, TSについてはパラメータ決め打ちのため、settingsボタンは表示しない
- TC → fieldName="AY"
- TS → fieldName="TS", index=[0, 0]

これらのデフォルト値の変更が必要な場合は、以下のファイルを修正
- `frontend/src/store/slice/InputNode/InputNodeSlice.ts`
- `studio/app/optinist/dataclass/tc.py`
- `studio/app/optinist/dataclass/ts.py`

2023-07-25 05:40 UTC, ReiHashimoto commented
TC, TSファイルから統計データへ変換するstat_file_convert関数を追加

TC, TSのノードをInputとして受け付ける

![Screenshot 2023-07-25 at 14 27 19](https://github.com/arayabrain/optinist-for-server/assets/42664619/c5ead406-15cc-4e2f-be44-6680416f5d2b)

関数のパラメータは現状これらを採用
![Screenshot 2023-07-25 at 14 35 19](https://github.com/arayabrain/optinist-for-server/assets/42664619/d22d2c04-1d78-491f-ad76-41448a56f80b)

この関数のoutputとして、polar plot, line graphを追加
cell単位での表示のため、indexのセレクトボックスからセレクトして表示
![Screenshot 2023-07-25 at 14 27 44](https://github.com/arayabrain/optinist-for-server/assets/42664619/3e8e44ba-50d9-43c1-9e96-07f8c908c6cf)


検証にあたっては、
matlabサンプルコードの実行に使用した
TC: AY_M37_ori004.mat
TS: ori004.mat

TC: AY_M44_OF_PRC_001.mat
TS: OF_PRC_001.mat

の2パターンの組み合わせを使用した。

2023-07-27 13:09 UTC, ReiHashimoto commented
curve_fittingを追加

ここまで実装した関数は以下のようなフローで結合できる
![Screenshot 2023-07-27 at 22 04 20](https://github.com/arayabrain/optinist-for-server/assets/42664619/7d05791b-06bb-490c-bed8-7ddd56acb9b2)

curve_fittingのoutput(チューニング幅のヒストグラム)
![Screenshot 2023-07-27 at 22 04 39](https://github.com/arayabrain/optinist-for-server/assets/42664619/4f3c9757-0c5d-427c-ad75-0bc68fbe782a)

2023-08-09 06:13 UTC, ReiHashimoto commented
- [ ] Oristats相当のファイルの仕様策定
  - できればMatlabでもロード可能な形式で
- [ ] バッチ処理でもOristats相当のファイルを生成し、保存する

2023-08-10 10:02 UTC, itutu-tienday commented
@ReiHashimoto 
- Note:
  - バッチ処理のテストコードの用意を、お願いしたいと思います。（処理仕様の確認を兼ね。まずは大枠のテストからでOK）

2023-08-21 08:57 UTC, ReiHashimoto commented
Experimentデータベース選択のノードを追加

![Screenshot 2023-08-21 at 17 55 33](https://github.com/arayabrain/optinist-for-server/assets/42664619/bc9a867b-baf6-4c49-a930-4eb268164b46)

ワークフロー構成
![Screenshot 2023-08-21 at 17 52 32](https://github.com/arayabrain/optinist-for-server/assets/42664619/31f1b7b6-cb6a-4c5b-866a-9a42b1d70a47)

2023-08-28 01:12 UTC, ReiHashimoto commented on studio/app/optinist/wrappers/stat/anova1_mult.py
> +    tukey = tukey_hsd(*data.T).confidence_interval()
tukey_hsdの導入により、処理全体の実行時間が大幅に増加したため、改善案要検討
- cell数180のデータで、従来2分弱だったところが、15分程度になった

matlabコード`anova1mult.m`の以下の処理に相当

```
sig=multcompare(anova_stats, alpha,'off');
```
- MATLABのmultcompareについて
  - https://jp.mathworks.com/help/stats/multcompare.html
  - matlabではanova1の結果を引数にすることで多重比較検定が実行できる

2023-08-28 05:43 UTC, itutu-tienday commented on studio/app/optinist/wrappers/stat/anova1_mult.py
> +    tukey = tukey_hsd(*data.T).confidence_interval()
@ReiHashimoto 
> cell数180のデータで、従来2分弱だったところが、15分程度になった

上記について、こちらの環境でも動作確認したところ、概ね同様の処理性能を確認しています。（1回の該当処理で、3-5秒程度要している）

なお cell数850件ほどのデータで動作確認したところ、予定では1時間前後で動作完了となりそうであるところ、処理が完了することを確認できていない状況です。
→ Mac, Windows にて確認
→ 動作中のログが不足しているため、処理中の状況の詳細は確認前

上記につき、一旦周辺の動作確認のため、該当のコードを暫定的にスキップするコードをご用意いただくことは可能でしょうか？ （tukey_hsd の性能改善は、別途調査する）

2023-08-28 11:17 UTC, itutu-tienday commented on studio/app/optinist/wrappers/stat/anova1_mult.py
> +    tukey = tukey_hsd(*data.T).confidence_interval()
@ReiHashimoto 
すでに調査されているかもしれませんが、こちらでも少し tukey_hsd の性能改善について調査していますので、以下へ調査メモを添付します。

- [tukey_hsd-performance-survey.md](https://github.com/arayabrain/optinist-for-server/files/12453799/tukey_hsd-performance-survey.md)

2023-08-29 01:30 UTC, itutu-tienday commented
@ReiHashimoto 

Visualize画面に関するレビュー指摘を以下へ記載しています。また後日に ご確認ください。
- https://github.com/arayabrain/optinist-for-server/issues/23#issuecomment-1696635217

また当PRのブランチ（feature/add-matlab-outputs）について、複数の開発内容がまとまっているため（node開発、batch開発、visualize画面）、可能であれば適度な単位で分割いただけるとよいかと考えます。
- https://github.com/arayabrain/optinist-for-server/tree/feature/add-matlab-outputs

2023-08-29 06:50 UTC, itutu-tienday requested changes
いくつかレビュー指摘を記載します。

2023-08-29 06:50 UTC, itutu-tienday commented on studio/app/const.py
> +TC_SUFFIX = "timecourse"
（対応は不要かもしれませんが、）
Experiment Database（Marmoset Brain Analysis ?）関連の定数は、`class FILETYPE` のように、何らかスコープを区切っておくと良いかもしれません。

2023-08-29 06:50 UTC, itutu-tienday commented on studio/app/optinist/wrappers/stat/__init__.py
> +    "stat": {
キーワードの最終fixは要顧客確認ですが、関数名など、以下のような名称で調整しても良いかもしれません。

- 現状)
  - stat
    - stats
- 調整案)
  - marmoset-brain-analysis  `# など。 または expdb など`
    - analyze-stats

2023-09-07 00:37 UTC, ReiHashimoto commented
以下のPRで対応のためクローズ
- #144 
- #145

2023-09-07 00:37 UTC, closed without merging