Feature/Workspace API
arayabrain/optinist-for-server pull request #58
Opened 2023-07-14 10:55 UTC by quanpython

2023-07-20 08:04 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
> +    user = db.query(common_model.User).get(workspace.user_id)
- The process does not seem to go through. (500 error)
- workspace.user_id should be set to the ID of the currently logged-in user.

2023-07-20 08:15 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
> +    return Workspace.from_orm(workspace)
Please check the delete flag.

2023-07-20 08:17 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
> +    db.delete(ws)
Deleting a workspace should be done with the delete flag On.

2023-07-20 08:22 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
> +    for key, value in data.items():
Are there items (primary key:id) that do not need to be updated that are being updated?

2023-07-20 08:24 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
> +    workspace = db.query(common_model.Workspace).get(id)
Please check the delete flag.

2023-07-20 08:25 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
> +    workspace = db.query(common_model.Workspace).get(id)
Please check the delete flag.

2023-07-20 22:12 UTC, itutu-tienday requested changes
@quanpython 
I have added the remarks. Please confirm.

2023-07-20 22:12 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
>      users = (
Please check users.active.

2023-07-21 02:33 UTC, quanpython commented on studio/app/common/routers/workspace.py
>      users = (
I already check active user in `get_current_user` dependence. Is it reasonable?

2023-07-21 02:44 UTC, ReiHashimoto requested changes

2023-07-21 02:44 UTC, ReiHashimoto commented on studio/__main_unit__.py
> +app.include_router(workspace.router, tags=["Workspace"])
Just coding style, please set tags in `router = APIRouter(...)`declaration like other routers.

2023-07-21 02:44 UTC, ReiHashimoto commented on studio/app/common/core/auth/auth_dependencies.py
> +            return User.from_orm(authed_user)
Could you refactor to separate this process into another function?
Almost same logic are used in both using firebase_token and using ex_token.

2023-07-21 02:44 UTC, ReiHashimoto commented on studio/config/docker/Dockerfile
> +
This code was removed in #52  and this PR seems to include commits in #52 .
Could you rebase to the latest develop-main?

2023-07-21 02:59 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
>      users = (
@quanpython 
Please check the active flag of the table (Common_model.User) that joins with WorkspacesShareUser, not the active flag of the logged in user (yourself).

2023-07-21 04:48 UTC, ReiHashimoto commented on studio/app/common/core/auth/auth_dependencies.py
> +            return User.from_orm(authed_user)
@quanpython 
smart refactor, thank you.

2023-07-21 04:52 UTC, ReiHashimoto approved these changes
LGTM

2023-07-21 05:06 UTC, itutu-tienday approved these changes

2023-07-21 05:07 UTC, itutu-tienday commented
@quanpython 
We have identified a series of corrections. Thank you very much.
We will proceed to the merge to develop-main once the Conflict has been resolved.

2023-07-21 07:59 UTC, merged