Feature/integrate api database
arayabrain/optinist-for-server pull request #64
Opened 2023-07-18 12:40 UTC by sanglevinh

2023-07-24 10:47 UTC, sanglevinh commented on frontend/src/pages/Database/Cells.tsx
> +      <DatabaseCells user={user}/>
> When displaying Cells View, it appears that a similar API is issued twice, is this the expected implementation? (*The same applies to Experiments View)
> 
> * Example
>   
>   * http://localhost:8000/expdb/experiments?offset=0&limit=50&sort=&sort=
>   * http://localhost:8000/expdb/experiments?offset=0&limit=50

I  have checked it.
It seems to be a bug with useEffect when I change the parameters in the router.
I changed the code in "https://github.com/arayabrain/optinist-for-server/pull/64/files#diff-2cdb1bd681169769aefb60edc1885b157e4fd91836dc6d90b2ce3e8f941c1d75R111-R123" it is resolved.
Similar for Experiments

2023-07-24 11:14 UTC, itutu-tienday requested changes

2023-07-24 11:14 UTC, itutu-tienday commented on frontend/src/pages/Database/Cells.tsx
> +      <DatabaseCells user={user}/>
When transitioning from the Experiments View to the Cells View, it is assumed that the Cells View will be filtered by Experiment ID.

However, the current API specification does not support searching by Experiment ID (string), so the API specification will be updated.

2023-07-24 11:14 UTC, itutu-tienday commented on frontend/src/pages/Database/Cells.tsx
> +      <DatabaseCells user={user}/>
When Cells View is displayed, Cells data is not displayed.

In the API response, Cells data is acquired.
In Experiments View, Experiments data is successfully displayed.

![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/2d1e3049-698e-4ee1-bcdd-dda598918083)

2023-07-25 00:08 UTC, itutu-tienday requested changes

2023-07-25 00:08 UTC, itutu-tienday commented on frontend/src/pages/Database/Cells.tsx
> +      <DatabaseCells user={user}/>
Add dummy data responses to the GET experiments,cells API. (already pushed to PR branch)

The above seems to have enabled the data to be displayed in the Cell View, but there seems to be a shortcoming in the implementation.

![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/d7721486-309c-499c-824f-8b217c740505)

2023-07-25 00:08 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +      <DataGridPro
The column headers do not seem to be displayed in the following places.

![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/e2076210-d1d8-47fb-b4b1-55ac739764b9)

2023-07-25 03:23 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +      <DataGridPro
> The column headers do not seem to be displayed in the following places.
> 
> ![image](https://user-images.githubusercontent.com/122338895/255752791-e2076210-d1d8-47fb-b4b1-55ac739764b9.png)

I check it with design. I think these two columns will not exist title

![image](https://github.com/arayabrain/optinist-for-server/assets/109060170/edea5dbb-1ff4-4877-84f5-865fe7dbd13a)

2023-07-25 03:46 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +      <DataGridPro
> The column headers do not seem to be displayed in the following places.
> 
> ![image](https://user-images.githubusercontent.com/122338895/255752791-e2076210-d1d8-47fb-b4b1-55ac739764b9.png)

I checked the api response. 
I see the header.graph_titles field is empty.
We are using header.graph_titles to display the column when header.graph_titles is empty the column is not visible

![Screen Shot 2023-07-25 at 10 39 41 AM](https://github.com/arayabrain/optinist-for-server/assets/109060170/9fdaf801-1d58-4d6b-a4dc-97df1d99e7e7)

2023-07-25 03:47 UTC, sanglevinh commented on frontend/src/pages/Database/Cells.tsx
> +      <DatabaseCells user={user}/>
> Add dummy data responses to the GET experiments,cells API. (already pushed to PR branch)
> 
> The above seems to have enabled the data to be displayed in the Cell View, but there seems to be a shortcoming in the implementation.
> 
> ![image](https://user-images.githubusercontent.com/122338895/255752150-d7721486-309c-499c-824f-8b217c740505.png)

I checked the api response.
I see the header.graph_titles field is empty.
We are using header.graph_titles to display the column when header.graph_titles is empty the column is not visible

2023-07-25 05:29 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +      <DataGridPro
I have an image of the document you are checking here (screen design v1.3)
*The font seems to be white in your environment?

![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/88bf0b2d-e0e8-4ce4-923c-f1435dd37312)

2023-07-25 05:35 UTC, itutu-tienday commented on frontend/src/pages/Database/Cells.tsx
> +      <DatabaseCells user={user}/>
As you informed us, it was due to header.graph_titles being from.

However, after setting header.graph_titles and checking the operation, the following problems seem to exist. Please refer to the attached image.

- "Pixel Image" is not displayed
- Graphs images have broken links (dict params embedded in the URL?)

<img width="1421" alt="image" src="https://github.com/arayabrain/optinist-for-server/assets/122338895/7a7fc359-ecd0-4a16-973a-5a7ddcf7cb57">

2023-07-25 05:37 UTC, itutu-tienday requested changes
I will comment reply.

2023-07-25 06:18 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +      <DataGridPro
> I have an image of the document you are checking here (screen design v1.3) *The font seems to be white in your environment?
> 
> ![image](https://user-images.githubusercontent.com/122338895/255797771-88bf0b2d-e0e8-4ce4-923c-f1435dd37312.png)


I understand. Now, I will implement it.

2023-07-25 07:03 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +      <DataGridPro
> I have an image of the document you are checking here (screen design v1.3) *The font seems to be white in your environment?
> 
> ![image](https://user-images.githubusercontent.com/122338895/255797771-88bf0b2d-e0e8-4ce4-923c-f1435dd37312.png)

I fixed it.

2023-07-25 07:04 UTC, sanglevinh commented on frontend/src/pages/Database/Cells.tsx
> +      <DatabaseCells user={user}/>
> As you informed us, it was due to header.graph_titles being from.
> 
> However, after setting header.graph_titles and checking the operation, the following problems seem to exist. Please refer to the attached image.
> 
> * "Pixel Image" is not displayed
> * Graphs images have broken links (dict params embedded in the URL?)
> 
> <img alt="image" width="1421" src="https://user-images.githubusercontent.com/122338895/255798286-7a7fc359-ecd0-4a16-973a-5a7ddcf7cb57.png">

I fixed it.

2023-07-25 08:34 UTC, itutu-tienday approved these changes
@sanglevinh 
Thanks, I have checked all the noted corrections.

2023-07-26 01:04 UTC, merged