Feature/database API
arayabrain/optinist-for-server pull request #69
Opened 2023-07-19 03:16 UTC by quanpython

2023-07-19 03:45 UTC, ReiHashimoto approved these changes
LGTM

2023-07-19 05:45 UTC, itutu-tienday requested changes

2023-07-19 05:45 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +        ).join(
Just to be sure, join with organizations table here as well.

2023-07-19 05:45 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +        .filter_by(publish_status=1)
For publish_status, please provide a constant

2023-07-19 05:53 UTC, itutu-tienday commented on studio/app/common/db/config.py
> -    MYSQL_DATABASE: str = Field(default=None, env="MYSQL_DATABASE")
(Question) Let me see why you are removing env="MYSQL_DATABASE"

2023-07-19 05:53 UTC, itutu-tienday commented on studio/app/common/db/config.py
> -    MYSQL_DATABASE: str = Field(default=None, env="MYSQL_DATABASE")
(Question) Where do I specify the DB port number (23306)?

2023-07-19 05:53 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +    current_user: User = Depends(get_current_user),
(Question)
How does get_current_user prepare data during development?
I would like to confirm the operation procedure.
(because accessing the API directly would result in a 401 error)

* I listed the following yesterday. Please let me know if you have any good ideas.
https://github.com/arayabrain/optinist-for-server/pull/52#discussion_r1266256675

2023-07-19 06:25 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +        .filter_by(publish_status=1)
```
class PublishFlags(str, Enum):
    on = "on"
    off = "off"
```
`publish_status` schemas is defined as string like above, but value in database is integer. 
Do you want to update this to integer or define another schema?

2023-07-19 06:50 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +        .filter_by(publish_status=1)
@quanpython 
At this time, I would like to have them defined separately for URL parameter constants and DB parameter constants.

2023-07-19 07:03 UTC, quanpython commented on studio/app/common/db/config.py
> -    MYSQL_DATABASE: str = Field(default=None, env="MYSQL_DATABASE")
> Where do I specify the DB port number (23306)?

You can specify DB port number along with DB host  in `MYSQL_SERVER` variable, for example `MYSQL_SERVER=localhost:23306`

If you use DB in docker-compose, specify DB server with DB container name is enough. 
In this case, use `MYSQL_SERVER='db'`

> Let me see why you are removing env="MYSQL_DATABASE"

Because DATABASE_URL is generated automatically from `assemble_db_connection` function:
```
    @validator("DATABASE_URL", pre=True)
    def assemble_db_connection(cls, v: Optional[str], values: Dict[str, Any]) -> Any:
        if isinstance(v, str):
            return v
        user = values.get("MYSQL_USER")
        password = values.get("MYSQL_PASSWORD")
        server = values.get("MYSQL_SERVER")
        database = values.get("MYSQL_DATABASE")
        return f"mysql+pymysql://{user}:{password}@{server}/{database}?charset=utf8mb4"
```

2023-07-19 07:38 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +    current_user: User = Depends(get_current_user),
- Do you want to be able to login on api-doc page to access APIs that require authentication?
   To do that, first login with /auth/login to get the access_token or ExToken, depend on USE_FIREBASE_TOKEN value.
   Then click `Authorize` with a lock icon on the top right, paste the token in the corresponding input boxes
- Or do you want a debug mode which automatically pass the `get_current_user` dependence with a specify user in `.env` file?

2023-07-19 08:36 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +    current_user: User = Depends(get_current_user),
@quanpython 
> Then click Authorize with a lock icon on the top right, paste the token in the corresponding input boxes

The above is OK. (I didn't understand this feature exactly)
Thanks for your answer.

2023-07-19 08:36 UTC, itutu-tienday commented on studio/app/common/db/config.py
> -    MYSQL_DATABASE: str = Field(default=None, env="MYSQL_DATABASE")
@quanpython 
I understand about the "DATABASE_URL."

I am asking about [Why env="MYSQL_DATABASE" was removed].
Is there any gap in understanding between the answers?

2023-07-19 09:11 UTC, quanpython commented on studio/app/common/db/config.py
> -    MYSQL_DATABASE: str = Field(default=None, env="MYSQL_DATABASE")
@itutu-tienday 
Oh, sorry for my confusion. I mistakenly removed MYSQL_DATABASE.
I will revert it and remove `env="DATABASE_URL"` instead.
Thank you.

2023-07-20 04:34 UTC, itutu-tienday approved these changes

2023-07-20 04:47 UTC, itutu-tienday requested changes
@quanpython 
I have added some remarks, please check them.

2023-07-20 04:47 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +                common_model.User.id == optinist_model.ExperimentShareUser.user_id,
Also check the users.active flag.

2023-07-20 04:47 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +                common_model.User.id == optinist_model.ExperimentShareUser.user_id,
Data with "experiments.share_type=2 (for organization)" should be made available to all members of the target organization.

2023-07-20 04:47 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +    query = (
`GET /expdb/cells` should incorporate the same specifications as `GET /expdb/experiments`.
-> Determine admin user vs. general user, use ExperimentShareUser, etc.

2023-07-20 10:22 UTC, itutu-tienday approved these changes

2023-07-20 10:34 UTC, itutu-tienday requested changes
@quanpython 
I have added some remarks. Please check them.

2023-07-20 10:34 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +    query = (
It seems that in some cases the actual number of acquisitions (less than 50) and the total of pagenation do not match.
-> Please check if the query and pagenation are working well together.
 -> If you need to provide sample data, please ask us.

2023-07-20 10:34 UTC, itutu-tienday commented on studio/app/common/schemas/users.py
> +        return self.role_id == 1
- Please separate is_admin and is_data_admin. (The difference is that is_admin can operate AccountManager)

- The condition for is_data_admin is as follows
  - `self.role_id == 1 or self.role_id == 10`

- Please define the value of role as a constant.
  ```
  1: admin
  10: data manager
  20: operator
  30: guest operator
  ```

- References
  - https://drive.google.com/drive/folders/1aiezc6vV16cxeLTFwKLaPdTrcYwyv3RQ

2023-07-21 02:41 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +    query = (
I can't reproduce it yet, please provide sample data

2023-07-21 03:03 UTC, itutu-tienday commented on studio/app/common/schemas/users.py
> +        return self.role_id == 1
@quanpython 
Thanks. One more point, please define and use a constant class (Enum) for Role.

2023-07-21 04:26 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +    query = (
@quanpython 
I will send sample data.
*API response results are also attached for reference.

[optinist-db-dump-20230721.zip](https://github.com/arayabrain/optinist-for-server/files/12116258/optinist-db-dump-20230721.zip)

2023-07-21 04:50 UTC, itutu-tienday approved these changes

2023-07-21 04:50 UTC, merged

2023-07-21 04:52 UTC, itutu-tienday commented
@quanpython  CC: @reactplus-thom 
There are some remaining tasks for this PR, but most of the points have been addressed, so I approve it once.
Please continue to investigate the following points in a separate PR.

- https://github.com/arayabrain/optinist-for-server/pull/69#discussion_r1270211726

2023-07-21 06:11 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +    query = (
@itutu-tienday  I investigated the error and created a PR #73