Feature/account API
arayabrain/optinist-for-server pull request #74
Opened 2023-07-21 10:33 UTC by quanpython

2023-07-24 02:48 UTC, itutu-tienday requested changes
@quanpython 
I will send you some pointers.

2023-07-24 02:48 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +async def list_user(db: Session):
The following error occurs during an API request, and it seems that the results cannot be obtained.
(Is it working properly in your environment?)

```
3 validation errors for LimitOffsetPage[User]
items -> 0 -> role_id
  field required (type=value_error.missing)
items -> 1 -> role_id
  field required (type=value_error.missing)
items -> 2 -> role_id
  field required (type=value_error.missing)
```

2023-07-24 03:05 UTC, itutu-tienday requested changes

2023-07-24 03:05 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        user_db = (
User information from different organizations should not be updated.

2023-07-24 03:05 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +            db.query(UserModel, UserRoleModel.role_id)
User information from different organizations should not be referenced.

2023-07-24 03:05 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        users = paginate(
User information from different organizations should not be referenced.

2023-07-24 03:05 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        user_db = (
Deletion of user information from different organizations should not be allowed.

2023-07-24 03:05 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        return User.from_orm(user_db)
It seems that a 400 error is always responded to after a successful update of user information.

```
{
  "detail": "No user record found for the given identifier (USER_NOT_FOUND)."
}
```

2023-07-24 07:55 UTC, quanpython commented on studio/app/common/core/users/crud_users.py
> +async def list_user(db: Session):
Because `paginate` function validates before return data. I made the `role_id` of User schemas optional and it worked.

2023-07-24 08:03 UTC, quanpython commented on studio/app/common/core/users/crud_users.py
> +        return User.from_orm(user_db)
Does the UID of that user exist on both Firebase and your database?

2023-07-24 08:41 UTC, ReiHashimoto commented on studio/app/common/routers/users_me.py
> +        current_user.uid, organization_id=current_user.organization_id
Maybe `db` required?

2023-07-24 09:38 UTC, itutu-tienday requested changes
Send pointers. Please confirm.

2023-07-24 09:38 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        user_db = (
If a non-existent user_id is specified, the response seems to be 400 (field validation error) instead of 404.

```
{
  "detail": "'NoneType' object has no attribute 'email'"
}
```

2023-07-24 09:38 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        assert user_db is not None, "User not found"
If the user does not exist, please respond with a 404 error. (currently a 400 error is being responded to)

2023-07-24 09:38 UTC, itutu-tienday commented on studio/app/common/routers/users_admin.py
>  @router.delete("/{user_id}")
The response to delete_user should return a success or failure (bool) of the process.

2023-07-24 09:38 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        db.commit()
When updating, please update the date and time (updated_at).

2023-07-24 09:38 UTC, itutu-tienday commented on studio/app/common/core/users/crud_users.py
> +        db.commit()
When deleting, please update the date and time (updated_at).

2023-07-25 00:56 UTC, itutu-tienday requested changes

2023-07-25 02:29 UTC, quanpython commented on studio/app/common/routers/users_admin.py
>  @router.delete("/{user_id}")
@ReiHashimoto  I just updated it

2023-07-25 02:55 UTC, itutu-tienday approved these changes
Responses to all points raised have been confirmed. Thank you.
I approve and merge the PR.

2023-07-25 02:55 UTC, merged