integrate api workspaces
arayabrain/optinist-for-server pull request #81
Opened 2023-07-26 08:44 UTC by sanglevinh

2023-07-27 06:08 UTC, itutu-tienday requested changes
I have noted the points raised. Please confirm.

2023-07-27 06:08 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +              {params.row.user_id === user?.id ? <EditIcon /> : ""}
Is it possible to single click (not double click) on the edit icon to get into edit name mode?

2023-07-27 06:08 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +                {params.row.name}
Regarding the name edit mode,
- I want to skip the update confirmation dialog display and update process if the name has not been changed.
- I want to cancel edit mode by pressing Esc key.

2023-07-28 01:21 UTC, itutu-tienday requested changes

2023-07-28 01:21 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +const columns = (
- At this time, the filter for each column should be turned off. (If implemented in the future, the filter will be executed on the backend.)
- Let the sorting of each column be performed on the back end.

2023-07-28 01:25 UTC, ReiHashimoto requested changes

2023-07-28 01:25 UTC, ReiHashimoto commented on frontend/src/store/slice/Workspace/WorkspaceType.ts
> +
If you create new type, please replace/remove existing same types.
Since `ItemsWorkspace` has been added, `WorkspaceType` is no longer required.

2023-07-28 01:25 UTC, ReiHashimoto commented on frontend/src/store/slice/Workspace/WorkspaceType.ts
> +
Since `data` has workspace items, `workspaces`is no longer required.

2023-07-28 01:25 UTC, ReiHashimoto commented on frontend/src/api/Workspace/index.ts
> +}
Why don't you use `WorkspaceDataDTO`?

2023-07-28 01:25 UTC, ReiHashimoto commented on frontend/src/store/slice/Workspace/WorkspaceSlice.ts
> +    })
Why don't you use `isAnyOf` matcher?

2023-07-28 01:25 UTC, ReiHashimoto commented on studio/app/common/schemas/workspace.py
> +    user_id: Optional[int]
Is this attribute required as API schema?

2023-07-28 04:19 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +              {params.row.user_id === user?.id ? <EditIcon /> : ""}
@ReiHashimoto Yes,  I can.
I will implement it.

2023-07-28 05:14 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +              {params.row.user_id === user?.id ? <EditIcon /> : ""}
@ReiHashimoto  I have done it. Pls, check it.

2023-07-28 05:16 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +                {params.row.name}
@ReiHashimoto 
I applied it.

2023-07-28 05:17 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +const columns = (
@ReiHashimoto 
I added filterable: false and sortable: false with comment // todo

2023-07-28 05:18 UTC, sanglevinh commented on frontend/src/store/slice/Workspace/WorkspaceType.ts
> +
@ReiHashimoto  I fixed it.

2023-07-28 05:19 UTC, sanglevinh commented on frontend/src/store/slice/Workspace/WorkspaceType.ts
> +
@ReiHashimoto 
I rename data => workspace and use WorkspaceDataDTO

2023-07-28 05:21 UTC, sanglevinh commented on frontend/src/api/Workspace/index.ts
> +}
@ReiHashimoto 
I rename Data => DataRequestEdit,
Because It is use api post or edit and api only used two attributes name and id.

2023-07-28 05:24 UTC, sanglevinh commented on studio/app/common/schemas/workspace.py
> +    user_id: Optional[int]
@ReiHashimoto I removed it.

2023-07-28 05:44 UTC, ReiHashimoto commented on frontend/src/api/Workspace/index.ts
> +}
@sanglevinh 
My apologies, I overlooked that it is a data type for POST.
Anyway, rename is required, thank you.

More requests.

- could you add expected response type annotations like other api call functions?
  - like `: Promise<SomeType>`
- please rename `DataRequestEdit` to `WorkspacePostDataDTO`
  - name of DataRequest may be understood in a broad sense

2023-07-28 06:16 UTC, ReiHashimoto requested changes

2023-07-28 06:39 UTC, sanglevinh commented on frontend/src/api/Workspace/index.ts
> +}
> @sanglevinh My apologies, I overlooked that it is a data type for POST. Anyway, rename is required, thank you.
> 
> More requests.
> 
> * could you add expected response type annotations like other api call functions?
>   
>   * like `: Promise<SomeType>`
> * please rename `DataRequestEdit` to `WorkspacePostDataDTO`
>   
>   * name of DataRequest may be understood in a broad sense

@ReiHashimoto  I applied it.

2023-07-28 06:39 UTC, sanglevinh commented on frontend/src/store/slice/Workspace/WorkspaceSelector.ts
> +  state.workspace.workspace
@ReiHashimoto  I removed it.

2023-07-28 06:39 UTC, sanglevinh commented on frontend/src/store/slice/Workspace/WorkspaceSlice.ts
> +          delWorkspace.fulfilled,
@ReiHashimoto  I removed it.

2023-07-28 09:03 UTC, itutu-tienday commented
@sanglevinh 
The following error seems to be occurring on the API side when displaying the Workspaces screen on the latest branch as of now.

```
File "/workspace/optinist-for-server/studio/app/common/routers/workspace.py", line 58, in search_workspaces
    ws.__dict__["user"] = db.query(common_model.User).get(ws.user_id)
AttributeError: 'Workspace' object has no attribute 'user_id'
```

It seems that the above user_id is being removed on the API side in commit 0bec77a8, but is the above error occurring in your environment?

2023-07-28 13:42 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +                {params.row.name}
@sanglevinh 
Thank you.
In addition, please make some adjustments as follows.

- When the focus is removed from a text field by mouse click, it should behave as follows.
  - If the edited content has been updated ... Same behavior as Enter key (edit confirmed)
  - If there is no change in the edited content ... Same behavior as the Esc key (cancel editing)

- When you press Enter or Esc to confirm/cancel an edit, the pencil icon seems to be highlighted. If possible, this highlighting should be turned off.
  - There are cases where highlighting remains as follows.
    - 
![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/90f5c6b7-c0c3-4744-94c3-75a9eefec161)

2023-07-31 05:29 UTC, ReiHashimoto commented on studio/app/common/routers/workspace.py
> +    for ws in data.items:
@quanpython 
Could you refactor the models?
(In other PR can be OK)

It seems relationship and FK is not defined in current models.

FYI
https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#one-to-many

I don't thik we have to insert User object into Workspace object like this process.

With relation, we can get User Object from user attribute.

2023-07-31 10:21 UTC, ReiHashimoto approved these changes
Backend requires refactor( as [this comment](https://github.com/arayabrain/optinist-for-server/pull/81/files#r1278806941)), but frontend looks fine.

2023-07-31 10:51 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +                {params.row.name}
As a minor point, it seems that the edit mode is not exited by clicking outside the edit column of the Workspace name when the following procedure is followed.

1. while editing the Workspace name, click on another column in the same row
2. after 1., clicking on another area does not exit the edit mode.

2023-07-31 10:53 UTC, itutu-tienday requested changes

2023-07-31 10:53 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +                {params.row.name}
As a minor point, it seems that the edit mode is not exited by clicking outside the edit column of the Workspace name when the following procedure is followed.

1. while editing the Workspace name, click on another column in the same row
2. after 1., clicking on another area does not exit the edit mode.

2023-07-31 11:20 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +                {params.row.name}
@itutu-tienday 
I added the code to path https://github.com/arayabrain/optinist-for-server/pull/81/files#diff-7f2d181bf721f32f4c28072d4027beb9f0678b00d15a2e0bf697b660ac30679aR460-R471
It is resolved.

2023-08-01 00:48 UTC, itutu-tienday approved these changes

2023-08-01 00:48 UTC, merged