update UI v1.4
arayabrain/optinist-for-server pull request #82
Opened 2023-07-27 03:00 UTC by sanglevinh

2023-07-27 05:12 UTC, itutu-tienday requested changes
I have noted the points raised. Please confirm.

2023-07-27 05:12 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>  ]
When transitioning from the Cells link of a record to Cells Viewer, Cells are not filtered by the target Experiment ID.

![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/f0e7ee5f-b689-4979-842b-c6765898c413)

2023-07-27 05:12 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
>    const offset = searchParams.get('offset')
Sorting not working on Experiment ID, Cell ID, columns?

2023-07-27 05:12 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
>  const columns = (handleOpenDialog: (value: string[]) => void) => [
Sorting not working on Experiment ID, Cell ID, columns?

2023-07-27 05:12 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
>  const columns = (handleOpenDialog: (value: string[]) => void) => [
Pixcel image, graph_urls, are not shown (broken link)

![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/fe62b669-2cb6-4c63-9216-a190983ac99b)

2023-07-31 07:59 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseCells.tsx
> +    headerName: 'Experiment ID',
@itutu-tienday I fixed it

2023-07-31 07:59 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
>      headerName: 'Experiment ID',
@itutu-tienday I fixed it

2023-07-31 08:01 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +  cell_image_urls: string[]
@itutu-tienday I fixed it

2023-07-31 08:01 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseCells.tsx
>  const columns = (handleOpenDialog: (value: string[]) => void) => [
@itutu-tienday I fixed it

2023-07-31 08:02 UTC, sanglevinh commented on frontend/src/store/slice/Database/DatabaseType.ts
> +  exp_id?: string
@itutu-tienday I fixed it

2023-07-31 08:03 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
>  ]
@itutu-tienday I fixed it

2023-07-31 08:03 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseCells.tsx
>    const offset = searchParams.get('offset')
@itutu-tienday I fixed it

2023-07-31 08:04 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseCells.tsx
>  const columns = (handleOpenDialog: (value: string[]) => void) => [
@itutu-tienday I fixed it

2023-07-31 08:04 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseCells.tsx
>  const columns = (handleOpenDialog: (value: string[]) => void) => [
@itutu-tienday I fixed it

2023-07-31 08:55 UTC, itutu-tienday approved these changes

2023-07-31 10:35 UTC, itutu-tienday requested changes
The remarks are noted.

2023-07-31 10:35 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
>      width: 160,
The thumbnail image ("thumb_url") does not seem to be displayed in the list.
-> Please display thumbnail images in the listings. (API v0.1.5)
-> Both cell image and plot image are covered.

2023-07-31 10:35 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseCells.tsx
> +        {params.row?.cell_image_url?.url && (
The thumbnail image ("thumb_url") does not seem to be displayed in the list.
-> Please display thumbnail images in the listings. (API v0.1.5)
-> Both cell image and plot image are covered.

2023-07-31 11:38 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseCells.tsx
> +        {params.row?.cell_image_url?.url && (
@itutu-tienday i fixed it

2023-08-01 00:59 UTC, itutu-tienday approved these changes

2023-08-01 06:46 UTC, merged