Feature/Update DB v0.3 and API v1.4
arayabrain/optinist-for-server pull request #83
Opened 2023-07-27 03:08 UTC by quanpython

2023-07-27 04:10 UTC, itutu-tienday requested changes
Some remarks are noted.

2023-07-27 04:10 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +            db.query(optinist_model.Experiment).get(item.experiment_uid).experiment_id
Are you not issuing a lot of SQL here?
→ Couldn't you handle this with a JOIN?

2023-07-27 04:10 UTC, itutu-tienday commented on studio/app/optinist/routers/expdb.py
> +            db.query(optinist_model.Experiment).get(item.experiment_uid).experiment_id
Are you not issuing a lot of SQL here?
→ Couldn't you handle this with a JOIN?

2023-07-27 10:05 UTC, quanpython commented on studio/app/optinist/routers/expdb.py
> +            db.query(optinist_model.Experiment).get(item.experiment_uid).experiment_id
@itutu-tienday  I implemented. Please check it

2023-07-27 10:40 UTC, itutu-tienday reviewed
@quanpython 
The points raised have been addressed and I think the PR is OK.
→ If there are no other issues, it would be good if we can merge them into the branch (#82) on the FrontEnd side. What do you think?

2023-07-27 10:54 UTC, quanpython commented
@itutu-tienday 
Yes, I agree with you. 
If there are no other issues. I will change the status of PR

2023-07-27 11:08 UTC, itutu-tienday approved these changes

2023-07-27 11:10 UTC, itutu-tienday commented
@quanpython 
> If there are no other issues. I will change the status of PR

Yes, please update PR and issue status.

2023-07-28 00:46 UTC, ReiHashimoto approved these changes

2023-07-28 01:02 UTC, merged