add role user
arayabrain/optinist-for-server pull request #86
Opened 2023-07-28 07:44 UTC by sanglevinh

2023-07-28 11:19 UTC, ReiHashimoto requested changes

2023-07-28 11:19 UTC, ReiHashimoto commented on frontend/src/pages/Account/index.tsx
> +          user && ROLE.ADMIN === user.role_id ?
it's better to use selector(UserSelector.ts)

2023-07-28 11:19 UTC, ReiHashimoto commented on frontend/src/pages/Workspace/index.tsx
> +      user && [ROLE.ADMIN, ROLE.MANAGER].includes(user.role_id) &&
define and use selector, too.

2023-07-31 07:15 UTC, itutu-tienday requested changes
The remarks are noted. Please check.

2023-07-31 07:15 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +            params.row.owner !== "User 2" && user && ([ROLE.ADMIN, ROLE.MANAGER].includes(user.role_id)) ?
Workspace share is available to all authorized users.
*I am updating the following design document as there may have been some confusion in the explanation. Please check it.

- https://drive.google.com/drive/folders/1aiezc6vV16cxeLTFwKLaPdTrcYwyv3RQ
  - 権限構成設計_v0.5.xlsx

2023-07-31 07:15 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +            params.row.owner !== "User 2" && user && ([ROLE.ADMIN, ROLE.MANAGER].includes(user.role_id)) ?
"User 2" is being compared and judged, but I think this is unnecessary processing, so please remove it.

2023-08-01 04:34 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +      user && [ROLE.ADMIN, ROLE.MANAGER].includes(user.role_id) &&
@ReiHashimoto i fixed it

2023-08-01 04:35 UTC, sanglevinh commented on frontend/src/pages/Dashboard/index.tsx
> +          {
@itutu-tienday i fixed it

2023-08-01 04:35 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +            params.row.owner !== "User 2" && user && ([ROLE.ADMIN, ROLE.MANAGER].includes(user.role_id)) ?
@itutu-tienday i fixed it

2023-08-01 04:35 UTC, sanglevinh commented on frontend/src/pages/Workspace/index.tsx
> +            params.row.owner !== "User 2" && user && ([ROLE.ADMIN, ROLE.MANAGER].includes(user.role_id)) ?
@itutu-tienday i fixed it

2023-08-01 04:55 UTC, sanglevinh commented on frontend/src/pages/Account/index.tsx
> +          user && ROLE.ADMIN === user.role_id ?
@ReiHashimoto i fixed it

2023-08-01 05:09 UTC, itutu-tienday requested changes

2023-08-02 08:42 UTC, sanglevinh commented on frontend/src/pages/Dashboard/index.tsx
> +              <LinkWrapper to="/console/account-manager">
@itutu-tienday 
I will fix it on branch 
https://github.com/arayabrain/optinist-for-server/tree/feature/account_manager

2023-08-03 01:33 UTC, itutu-tienday commented on frontend/src/pages/Dashboard/index.tsx
> +              <LinkWrapper to="/console/account-manager">
@sanglevinh 
Thanks.
- If there is no problem, could you merge the current contents of #86 into #93?  
(I will reconfirm the action in #93)

2023-08-03 01:40 UTC, itutu-tienday commented
@ReiHashimoto 
当PRへのレビュー指摘が対応されていますので、また確認をお願いします。
(Please check back as the review remarks to this PR have been addressed.)

2023-08-03 03:13 UTC, sanglevinh commented on frontend/src/pages/Dashboard/index.tsx
> +              <LinkWrapper to="/console/account-manager">
@itutu-tienday I have merged it, please check it for me.
https://github.com/arayabrain/optinist-for-server/pull/93

2023-08-04 04:24 UTC, ReiHashimoto approved these changes
LGTM

2023-08-04 05:52 UTC, itutu-tienday approved these changes

2023-08-04 06:26 UTC, merged