Integrate API Share Workspace, Database
arayabrain/optinist-for-server pull request #87
Opened 2023-07-28 13:03 UTC by sanglevinh

2023-07-31 02:21 UTC, itutu-tienday requested changes

2023-07-31 02:21 UTC, itutu-tienday commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
Deactivating share to user does not delete the user record. (Before implementation?)

2023-08-02 04:30 UTC, itutu-tienday requested changes

2023-08-02 04:30 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +            <Box
(Bug) Are Share, Publish links displayed even if the user does not have administrative privileges?

2023-08-02 04:30 UTC, itutu-tienday commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
When deleting a user (from the delete icon), delete the record row.

2023-08-02 04:30 UTC, itutu-tienday commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
If "Share for Organization" is selected, delete the user list. (The user list appears to remain in the DB.)
\* Please also make necessary cooperation with the BackEnd side.

2023-08-02 04:30 UTC, itutu-tienday commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
If the share type is "Share for Users" and the user list is empty, please set the share type to "No Share" when registering data.
\* Please make necessary cooperation with BackEnd side as well.

2023-08-02 04:30 UTC, itutu-tienday commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
In Database Share, I have only registered one user, but the list of all users appears to be registered.
\* Is this a problem on the API side? (`GET /expdb/share/{id}/status`)

2023-08-02 04:30 UTC, itutu-tienday commented on frontend/src/components/PopupShare.tsx
> +          <Button onClick={() => handleClose(false)}>Cancel</Button>
This is a minor request, but please make the Esc key press the same action as the Cancel click (close the dialog).

2023-08-02 05:04 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +            <Box
@itutu-tienday 
If you log out and then log in again, the user is not updated.
I added on line https://github.com/arayabrain/optinist-for-server/pull/87/files#diff-762d53d3c900be0fa9e7beac54cc9503a5c211188e65d344339521ad7daa01d9R31

It resolved.

2023-08-02 05:05 UTC, sanglevinh commented on frontend/src/components/PopupShare.tsx
> +          <DialogContent sx={{minHeight: 500}}>
@itutu-tienday 
I fixed it.

2023-08-02 05:05 UTC, sanglevinh commented on frontend/src/components/PopupShare.tsx
> +          <DialogContent sx={{minHeight: 500}}>
@itutu-tienday 
I fixed it.

2023-08-02 05:11 UTC, sanglevinh commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
@itutu-tienday 
Yes, I noticed that the API PUT method was not updating users in the database. 
This issue has been fixed in the pull request at https://github.com/arayabrain/optinist-for-server/pull/92

2023-08-02 05:46 UTC, itutu-tienday requested changes

2023-08-02 05:46 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +            <Box
@sanglevinh 
Thank you. However, it still does not seem to be resolved on my end.
For example, if I sign in again with a user with role=20(operator), the share/publish link does not seem to be hidden. (The API request returns a 403).

-> Is there something wrong with the environment on our side? (cache, etc.?)

2023-08-02 05:46 UTC, itutu-tienday commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
@sanglevinh 
Understood.
-> If all is well, could you please incorporate the contents of #92 into this branch (#87)? (#92 has already been reviewed briefly)

2023-08-02 07:51 UTC, sanglevinh commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +            <Box
@itutu-tienday 
Oh, I'm sorry about that problem. Regarding decentralization, we have a dedicated pull request for it.
https://github.com/arayabrain/optinist-for-server/pull/86

2023-08-02 07:53 UTC, sanglevinh commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
@itutu-tienday 
I merged it.

2023-08-02 07:54 UTC, sanglevinh commented on frontend/src/components/PopupShare.tsx
> +          <Button onClick={() => handleClose(false)}>Cancel</Button>
@itutu-tienday 
I added it.

2023-08-02 07:55 UTC, sanglevinh commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
@itutu-tienday 
I fixed it.

2023-08-02 07:55 UTC, sanglevinh commented on frontend/src/components/PopupShare.tsx
> +      field: "share",
@itutu-tienday 
I fixed it.

2023-08-02 08:20 UTC, itutu-tienday requested changes

2023-08-02 08:20 UTC, itutu-tienday commented on frontend/src/components/PopupShare.tsx
> +          <Button onClick={() => handleClose(false)}>Cancel</Button>
@sanglevinh 
Sorry, I was expecting the Esc key press to "close the Dialog", is it implemented that way? (I'm asking because the Esc key doesn't seem to close the Dialog.)

2023-08-02 08:20 UTC, itutu-tienday commented on frontend/src/components/Database/DatabaseExperiments.tsx
> +            <Box
@sanglevinh 
Yes, that's right. Understood.
PR #86 is confirmed to work, so we will close this one.

2023-08-02 10:01 UTC, itutu-tienday approved these changes

2023-08-04 06:31 UTC, ReiHashimoto approved these changes

2023-08-04 06:33 UTC, merged