Update workflow navigatioin
arayabrain/optinist-for-server pull request #89
Opened 2023-07-31 22:40 UTC by ReiHashimoto

- #21 

- #81 をベースにしているため、マージ後にdevelop-mainにrebaseします
  - 最後のコミットをご確認ください

## 変更点
- Workspaces画面からWorkflow, Results画面への遷移を追加
- Workflow画面でWorkspaceのオーナーではない場合にRUNボタンを非活性にする制御を追加
  - 別途API側でも認証・権限チェックをかけておく必要はあると思われるため、こちらは追って対応予定

## 備考
- WorkspaceのIDの型定義がnumber, string混在していたため、numberに寄せています

2023-08-01 03:16 UTC, itutu-tienday requested changes

2023-08-01 03:16 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +      <ButtonCustom onClick={() => handleNavWorkflow(params.row.id)}>Workflow</ButtonCustom>
異なるworkspace_idで、Workflow画面や Results画面へアクセスした際、同じWorkflow,Results情報が表示されるようです。
※まだ調整前の段階でしたでしょうか？

2023-08-01 03:16 UTC, itutu-tienday commented on frontend/src/pages/Workspace/index.tsx
> +      <ButtonCustom onClick={() => handleNavWorkflow(params.row.id)}>Workflow</ButtonCustom>
Workflow画面や Results画面 へ遷移した際、URLは同じ内容（/workspace/{workspace_id}）となっていますが、ここは今回 仕様変更を入れる予定はありませんでしたでしょうか。
（念のため確の認。この仕様でも、特に課題はないと思われる）

2023-08-07 03:59 UTC, ReiHashimoto commented on frontend/src/pages/Workspace/index.tsx
> +      <ButtonCustom onClick={() => handleNavWorkflow(params.row.id)}>Workflow</ButtonCustom>
@itutu-tienday 
修正を行いましたので、動作確認いただければと思います。

Results画面などのタブ管理は一旦stateのみでの管理としようと考えています

2023-08-08 04:56 UTC, ReiHashimoto commented
共有されたworkspaceの場合、recordsの削除ボタンを表示しないように修正しました

![Screenshot 2023-08-08 at 13 54 11](https://github.com/arayabrain/optinist-for-server/assets/42664619/66f0f166-5b28-4b1f-9e18-07da2cc345e7)

2023-08-08 05:33 UTC, itutu-tienday approved these changes

2023-08-08 05:33 UTC, merged