Feature/refactor db models and fix some bugs
arayabrain/optinist-for-server pull request #92
Opened 2023-08-02 02:39 UTC by quanpython

2023-08-03 02:06 UTC, itutu-tienday requested changes

2023-08-03 02:06 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
>  ):
@quanpython 

Please add the following fields to the model Workspace
- shared_count (number of shared users)

\* The above information is reflected in the API documentation v0.1.7.
- https://drive.google.com/drive/folders/1vCyE0B8kMcZZgymXMnVt-_PYMRlHD20a
  - optinist-server-apidoc-v0.1.7.html

2023-08-04 06:25 UTC, ReiHashimoto requested changes
apply same changes (add relationship and FK) for all models.

- User
  - organization
- UserRole
  - user
  - role
- WorkspaceShareUser
  - workspace
  - user
- Experiment
  - organization
- ExperimentShareUser
  - experiment
  - user

2023-08-04 06:44 UTC, itutu-tienday requested changes

2023-08-04 06:44 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
>  ):
@quanpython 
The above seems to have been addressed in 083f68d, but we have identified the following issue.

- In some cases, the number of user lists obtained by `GET /workspace/share/{id}/status` and shared_count do not match.
  - -> Probably due to the difference in flag judgments such as active in the users table.

Please check and adjust the above.

2023-08-07 02:26 UTC, itutu-tienday commented on studio/app/common/routers/workspace.py
>  ):
Note: Correction confirmed at 671087c.

2023-08-07 02:37 UTC, itutu-tienday approved these changes

2023-08-07 04:53 UTC, ReiHashimoto approved these changes
LGTM

2023-08-07 05:06 UTC, merged