add Account Manager Page
arayabrain/optinist-for-server pull request #93
Opened 2023-08-02 09:26 UTC by sanglevinh

2023-08-03 06:01 UTC, itutu-tienday requested changes

2023-08-03 06:01 UTC, itutu-tienday commented on frontend/src/pages/AccountManager/index.tsx
> +  const columns = useMemo(() =>
Please make it filterable (partial text match) by UserName, Mail,.

\* Described in Screen Design Document v1.5
- https://drive.google.com/drive/folders/1OZgVlIx-ZxP_BUjB0EAvaExYKc3MhaH-
  - 画面設計_v1.5.pptx

2023-08-04 06:28 UTC, ReiHashimoto requested changes

2023-08-04 06:45 UTC, sanglevinh commented on frontend/src/pages/Login/index.tsx
> +        await dispatch(getMe())
@ReiHashimoto We use getMe() every time the user logs in again to check their permissions, and we observe that it is only called once.

2023-08-04 06:54 UTC, sanglevinh commented on frontend/src/utils/checkRole.ts
> +export const isMe = (user?: UserDTO, idUserWorkSpace?: number) => {
sorry, i converted isMe() to isMine()

2023-08-04 06:57 UTC, ReiHashimoto commented on frontend/src/pages/Login/index.tsx
> +        await dispatch(getMe())
@sanglevinh 
My apologies. My check wasn't enough, works fine.

2023-08-04 06:57 UTC, sanglevinh commented on frontend/src/store/slice/User/UserSlice.ts
> +      )
@ReiHashimoto i fixed it

2023-08-04 06:58 UTC, sanglevinh commented on frontend/src/api/users/UsersApiDTO.ts
> +  update_at?: string
@ReiHashimoto sorry, i fixed it

2023-08-04 07:02 UTC, sanglevinh commented on frontend/src/components/Layout/LeftMenu.tsx
> +    navigate('/console/account-manager?sort=&sort=&limit=50&offset=0')
@ReiHashimoto i fixed it, I encounter the same workspace with a similar path: '/console/workspaces?limit=50&offset=0'. Would you like me to change it to '/console/workspaces'?

2023-08-04 07:35 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
> +  const columns = useMemo(() =>
@itutu-tienday We have added this section, please check it out for us.

2023-08-04 07:35 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
> +  const columns = useMemo(() =>
@itutu-tienday We have added this section, please check it out for us.

2023-08-04 07:42 UTC, ReiHashimoto commented on frontend/src/components/Layout/LeftMenu.tsx
> +    navigate('/console/account-manager?sort=&sort=&limit=50&offset=0')
@sanglevinh 
Thank you for your implementation.

As you describe, I want the same fix to be applied  to `/console/workspaces`, either.

However, wIth just removing query parameters, api seems to be called twice.
- `/admin/users?limit=50&offset=0`
- `/admin/users?sort=&sort=&limit=50&offset=0`

Let's address these fix in a separate Issue.
So, could you put url back to `'/console/account-manager?sort=&sort=&limit=50&offset=0'` again for now?

2023-08-04 07:51 UTC, sanglevinh commented on frontend/src/components/Layout/LeftMenu.tsx
> +    navigate('/console/account-manager?sort=&sort=&limit=50&offset=0')
@ReiHashimoto, i fixed it

2023-08-04 08:36 UTC, ReiHashimoto requested changes

2023-08-04 08:36 UTC, ReiHashimoto commented on frontend/src/@types/index.ts
> +  DATA_MANAGER = 10,
Apply change to
- `frontend/src/store/slice/User/UserSelector.ts`

2023-08-04 08:38 UTC, itutu-tienday commented on frontend/src/pages/AccountManager/index.tsx
> +  const columns = useMemo(() =>
@sanglevinh 
Thank you. I will mention a few things I noticed.

- Sorting does not seem to be working in Role column. (API seems to be returning an error 400)
- The filter condition for UserName and Mail should be contain only. 
  - -> Similar to the ExperimentID filter in the Database screen.

2023-08-04 09:45 UTC, sanglevinh commented on frontend/src/@types/index.ts
> +  DATA_MANAGER = 10,
@ReiHashimoto i fixed it

2023-08-04 09:56 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
> +  const columns = useMemo(() =>
@itutu-tienday 

- sorting: I checked and reported BE to correct it
- filter: I fixed it to only be able to filter by contains
Please kindly recheck it.

2023-08-04 10:06 UTC, ReiHashimoto approved these changes
LGTM

2023-08-04 10:56 UTC, ReiHashimoto requested changes
sorry, I’ve overlooked.

access to `/console/account-manager` directory, we can see the page.
tables are empty, but non-admin users should be redirected to /console.

2023-08-07 03:02 UTC, sanglevinh commented
> sorry, I’ve overlooked.
> 
> access to `/console/account-manager` directory, we can see the page. tables are empty, but non-admin users should be redirected to /console.
@ReiHashimoto 
I fixed it.

2023-08-07 06:48 UTC, ReiHashimoto approved these changes
LGTM

2023-08-10 04:44 UTC, itutu-tienday approved these changes

2023-08-10 08:41 UTC, merged