Feature: Cancel workflow
arayabrain/optinist-for-server pull request #94
Opened 2023-08-03 02:49 UTC by quanpython

2023-08-03 09:41 UTC, itutu-tienday requested changes

2023-08-03 09:41 UTC, itutu-tienday commented on studio/app/common/core/workflow/workflow_result.py
> +            return False
If there is no data to process, it is appropriate to leave the response code as 404 or similar.

2023-08-03 09:41 UTC, itutu-tienday commented on studio/app/common/core/workflow/workflow_result.py
> +    def cancel(self):
(Question) This may be difficult to deal with, but would it be difficult to interrupt the `conda activate` at the beginning of the process?

2023-08-03 09:46 UTC, itutu-tienday requested changes

2023-08-03 09:56 UTC, itutu-tienday commented
@ReiHashimoto 
当PRについて、動作確認を行い（Mac, Windows）、基本的には期待する動作が行われていることを確認しています。

ただし、以下の様な課題を確認しています。
1. Workflow処理冒頭の `conda activate` は停止できていない
    - → Snakemakeの仕様から、対応は難しいかもしれない。（対応優先度は低い）
3. WorkflowをCancelすると、そのWorkflowは強制終了状態（≒Workflowデータ破損）となるようで、画面上はRUNは行えるが、次回のRUNに必ず失敗する模様。
    - → 利用シーンを想定すると、これは再度RUNできることが（100%ではなくとも）求められると思われる。

上記の 2. について対処が必要と想定されますが、対応方法について、協議をできればと思います。

2023-08-03 12:51 UTC, quanpython commented on studio/app/common/core/workflow/workflow_result.py
> +    def cancel(self):
I will investigate further

2023-08-03 13:14 UTC, quanpython commented on studio/app/common/core/logger.py
> +                    else:
@itutu-tienday

> Stopping the PID of one workflow will also stop other workflows that are running


Conflicts occur when logging, for example when I stop a workflow, an error is thrown and it stops as intended. However, other running workflows also receive similar error messages and return errors to the client side, even though they are still running.

Solution:

- Save execution script file path along with PID of each workflow. (Because every time a workflow runs, Snakemake creates a copy with a unique random name for the execution script)
- Add a condition that only returns an error if the error message contains the name of the script file. This way, workflows executed by other files will continue to run normally.

2023-08-07 02:37 UTC, itutu-tienday commented on studio/app/common/core/workflow/workflow_result.py
> +    def cancel(self):
Note:  Correction confirmed at c928476

2023-08-08 02:23 UTC, itutu-tienday commented on studio/app/common/core/logger.py
> +                    else:
@quanpython 
Since we do not yet have the details of the issue, here are a few questions

> Conflicts occur when logging,. 

Does this mean that the issue is that multiple processes share the snakemake log output destination?
-> If so, can't we work around this by separating log files for each process? (Need to check the snakemake specs)

> Save execution script file path along with PID of each workflow. 

Where do we save the above information?

> Add a condition that only returns an error if the error message contains the name of the script file.

Where is the above condition supposed to be written?

2023-08-08 07:26 UTC, quanpython commented on studio/app/common/core/logger.py
> +                    else:
@itutu-tienday
>Does this mean that the issue is that multiple processes share the snakemake log output destination? 
 
Multiple processes don't share the snakemake log output destination, they only share the log output message at same time. 
It means when one process has one log output message, it is saved to log file of all running process.
You can verify it by run multiple workflow at same time, then check log file of snakemake in `ROOT_DIR/.snakemake/log`. You can see the log content of workflow which run before, contains all log content of workflows which run after that.

> Where do you save the above information?

Currently, I save them in output directory of each workflow:
```python
# OUTPUT_DIR/workspace_id/unique_id/pid.json
{
	"last_pid": 123,  # last PID of workflow
	"last_script_file": ".snakemake/scripts/tmp_6ra21am.func.py", # last script file of workflow
}
```

> Where is the above condition supposed to be written?

It is write in `studio/app/common/core/logger.py`
```python
if "Signals.SIGTERM" in msg["msg"]:  # Check if the message is thrown by killing process action
	pid_filepath = join_filepath([
		DIRPATH.OUTPUT_DIR,
		self.workspace_id,
		self.unique_id,
		"pid.json",
	])
	pid_data = JsonReader.read(pid_filepath)
	if pid_data["last_script_file"] in msg["msg"]: # Check if error message contains the name of the script file
		self.logger.error("Workflow cancelled")
```
For example, when I kill one process, a message like this is thrown:
```
Full Traceback (most recent call last):
  File "/home/admin/miniconda3/envs/optinistfs/lib/python3.8/site-packages/snakemake/script.py", line 455, in evaluate
...
subprocess.CalledProcessError: Command 'source /home/admin/miniconda3/bin/activate '/home/admin/Documents/optinistfs/.snakemake/conda/4f38a0cc21fc784d8a6ce790ae65ca67_'; set -euo pipefail;  python /home/admin/Documents/optinistfs/.snakemake/scripts/tmp_6ra21am.func.py' died with <Signals.SIGTERM: 15>.
```
It contains `<Signals.SIGTERM: 15>` , shows that the process is killed by user and `.snakemake/scripts/tmp_6ra21am.func.py`  is last execute script file path.

2023-08-09 04:33 UTC, itutu-tienday commented on studio/app/common/core/logger.py
> +                    else:
@quanpython 
I understand your situation.

I imagine it would be better if the above issue could be avoided by setting up snakemake.
It would be good if you could investigate the log output specification of snakemake. (e.g., separate logs between processes, etc.).
What do you think?

2023-08-10 03:43 UTC, quanpython commented on studio/app/common/core/logger.py
> +                    else:
@itutu-tienday
I've investigated the Snakemake docs but can't find any details about logging. I think it's a general problem of the `logging` library.

Since there is currently only one process to handle the log of all workflows, I tried running snakameke with `multiprocessing` for the purpose of isolating the logging processes.
It seems to solve the logging problem but snakemake doesn't work as expected (sometimes it crashes or keeps running without results)

2023-08-10 07:04 UTC, itutu-tienday commented on studio/app/common/core/logger.py
> +                    else:
@quanpython 
Thank you for your research. I understand.

If there is nothing else that you feel can be investigated, please put the logging issue on hold for now. We will also investigate the matter.

2023-08-24 10:06 UTC, itutu-tienday commented on studio/app/common/core/logger.py
> +                    else:
The following SOLUTION confirms that it seems to be OK to respond.

- https://github.com/arayabrain/optinist-for-server/pull/94#discussion_r1283187732

2023-08-24 10:44 UTC, itutu-tienday requested changes

2023-08-24 10:44 UTC, itutu-tienday commented on studio/app/common/core/logger.py
> +                    if any(
@quanpython 
We have checked the operation and confirmed that it seems to be working as expected with the suggested modifications.
Thank you.

Therefore, please add your technical comments (intent of adding the code) to the code you have added this time.

2023-08-29 09:19 UTC, itutu-tienday requested changes

2023-08-29 09:19 UTC, itutu-tienday commented on studio/app/common/core/workflow/workflow_result.py
> +    def cancel(self):
@quanpython 
I would like to close the above TODO once and for all.
Therefore, please leave your TODO comments on the issues you are currently aware of.

2023-08-30 01:45 UTC, itutu-tienday commented on studio/app/common/core/workflow/workflow_result.py
> +    def cancel(self):
@quanpython 

Thanks for adding your comment.
Do you have any additional information on the following that you have found out?

> > (Question) This may be difficult to deal with, but would it be difficult to interrupt the conda activate at the beginning of the process?

> I will investigate further

2023-08-30 03:50 UTC, itutu-tienday commented
対応状況メモ）

> ただし、以下の様な課題を確認しています。
> 
> 1. Workflow処理冒頭の `conda activate` は停止できていない

→ この課題は残っている。 ※現時点では仕様（注意事項）となる見込み。

> 2. WorkflowをCancelすると、そのWorkflowは強制終了状態（≒Workflowデータ破損）となるようで、画面上はRUNは行えるが、次回のRUNに必ず失敗する模様。

→ 一定の対処は実施。（for Windows）
ただし、次回のRUNが失敗する状況は、要因の複合も想定されるため、別途調査想定。

> 3. 以下の内容
>    
>    * [Feature: Cancel workflow #94 (comment)](https://github.com/arayabrain/optinist-for-server/pull/94#discussion_r1283187732)

→ 複数WF実行時のプロセスkillの課題については、一定の対処は適用済。（loggerの呼び出し元プロセスをチェックする対処）

2023-08-30 07:57 UTC, quanpython commented on studio/app/common/core/workflow/workflow_result.py
> +    def cancel(self):
@itutu-tienday
I inspected the code in the snakemake library and observed the workflow being executed at the line "https://github.com/snakemake/snakemake/blob/main/snakemake/shell.py#L258". 
```
        proc = sp.Popen(
            cmd,
            bufsize=-1,
            shell=use_shell,
            stdout=stdout,
            universal_newlines=iterable or read or None,
            close_fds=close_fds,
            **cls._process_args,
            env=envvars,
        )
```
The `cmd` variable has the following format:
```
source /home/admin/miniconda3/bin/activate '/home/tuanna/Documents/optinistfs/.snakemake/conda/491889952d2f07f3876bb801eea626e9_'; set -euo pipefail; python /home/admin/Documents/optinistfs/.snakemake/scripts/tmp03froqxo.func.py
```
Because the algorithm function runs immediately after activating the environment, I think interrupting `conda activate` process is the same as interrupting the algorithm function.

2023-08-30 08:22 UTC, itutu-tienday commented on studio/app/common/core/workflow/workflow_result.py
> +    def cancel(self):
@quanpython 
Ah, so the generation of the pid.json file is done after `conda create env` and `conda activate`?
If so, it is impossible to stop `conda create env` or `conda activate` with the Cancel API?
(Am I correct in my understanding above?)

If the above understanding is correct, I will ask you to comment the above notes in the source code of the API and approve this PR.

2023-08-30 12:12 UTC, quanpython commented on studio/app/common/core/workflow/workflow_result.py
> +    def cancel(self):
@itutu-tienday

Yes, `conda activate` is only called when each algorithm function executes and right after function is complete, the env is deactivated. It is not a separate process that running from the beginning of the whole workflow, so it cannot be interrupted.

I have commented the above notes in the source code. Let me know if there are any problems.

2023-08-31 02:25 UTC, itutu-tienday approved these changes

2023-08-31 02:26 UTC, merged