create user
arayabrain/optinist-for-server pull request #96
Opened 2023-08-03 11:23 UTC by sanglevinh

2023-08-04 04:53 UTC, ReiHashimoto requested changes

2023-08-04 04:53 UTC, ReiHashimoto commented on frontend/src/pages/AccountManager/index.tsx
> +        break;
please use enum `ROLE`

2023-08-04 04:53 UTC, ReiHashimoto commented on frontend/src/pages/AccountManager/index.tsx
> +   }: ModalComponentProps) => {
just styling, unnecessary 1 spaces.

2023-08-04 04:53 UTC, ReiHashimoto commented on frontend/src/pages/AccountManager/index.tsx
> +          {!dataEdit?.uid ? (
password form appears on Edit modal.

![Screenshot 2023-08-04 at 13 47 04](https://github.com/arayabrain/optinist-for-server/assets/42664619/b0bbd056-32a4-4a7d-977f-dd3e173e992f)

2023-08-04 04:53 UTC, ReiHashimoto commented on frontend/src/pages/AccountManager/index.tsx
> +            value={formData?.role_id || ''}
can you set current role as initial value on Edit modal?

2023-08-04 07:11 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
> +          {!dataEdit?.uid ? (
@ReiHashimoto, This Pull Request is not related to editing the user, so can I disable the edit button and make the necessary changes in a separate Pull Request specifically created for editing the user?

2023-08-04 07:31 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
> +   }: ModalComponentProps) => {
@ReiHashimoto i fixed it

2023-08-04 07:37 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
> +            value={formData?.role_id || ''}
@ReiHashimoto This Pull Request is not related to editing the user, so can I disable the edit button and make the necessary changes in a separate Pull Request specifically created for editing the user?

2023-08-04 08:44 UTC, ReiHashimoto commented on frontend/src/pages/AccountManager/index.tsx
> +          {!dataEdit?.uid ? (
@sanglevinh 
OK, please disable edit button and leave to do comment.

2023-08-04 08:44 UTC, ReiHashimoto commented on frontend/src/pages/AccountManager/index.tsx
> +            value={formData?.role_id || ''}
same as
https://github.com/arayabrain/optinist-for-server/pull/96#discussion_r1284155886

2023-08-04 08:55 UTC, ReiHashimoto commented on frontend/src/pages/AccountManager/index.tsx
> +   }: ModalComponentProps) => {
@sanglevinh 
It seems to be not fixed.

My request is, 
```
const ModalComponent =
___({  // indent with 3 spaces → 2spaces
_____onSubmitEdit, // indent with 5spaces → 4spaces
...
```

2023-08-04 10:33 UTC, ReiHashimoto commented on frontend/src/pages/AccountManager/index.tsx
> +   }: ModalComponentProps) => {
@sanglevinh 
sorry for not making my intention clear enough, too.
I found it fixed, thank you.

2023-08-08 00:27 UTC, ReiHashimoto approved these changes

2023-08-10 04:51 UTC, merged