edit account
arayabrain/optinist-for-server pull request #97
Opened 2023-08-04 10:27 UTC by sanglevinh

2023-08-09 02:40 UTC, sanglevinh commented on frontend/src/store/slice/User/UserActions.ts
> +    {id: number, data: UpdateUserDTO, params: WorkspaceParams}
@ReiHashimoto i fixed it

2023-08-09 23:57 UTC, ReiHashimoto commented on frontend/src/store/slice/User/UserActions.ts
> +    {id: number, data: UpdateUserDTO, params: WorkspaceParams}
@sanglevinh OK, but import WorkspaceParams remains in Line 8.

2023-08-10 02:03 UTC, sanglevinh commented on frontend/src/store/slice/User/UserActions.ts
> +    {id: number, data: UpdateUserDTO, params: WorkspaceParams}
@ReiHashimoto sorry for the omission, i deleted it

2023-08-10 05:10 UTC, itutu-tienday requested changes

2023-08-10 05:10 UTC, itutu-tienday commented on frontend/src/pages/AccountManager/index.tsx
> +            alert('This email already exists!')
@sanglevinh 
- Message display (both success and error) should be in snackbar format.
  - If the implementation is not simple, please contact us.
  - Please do the same for the AccountManager screen, except here.

- Sample images
  - ![image](https://github.com/arayabrain/optinist-for-server/assets/122338895/2ef9ee30-bb55-440d-91f2-9d73535ed516)

2023-08-10 07:04 UTC, sanglevinh commented on frontend/src/pages/AccountManager/index.tsx
> +            alert('This email already exists!')
@itutu-tienday ie we only do it in the AccountManager screen including operations: edit, add, delete accounts right?

2023-08-10 07:40 UTC, itutu-tienday commented on frontend/src/pages/AccountManager/index.tsx
> +            alert('This email already exists!')
@sanglevinh 
Yes, I assume so.

Then, since support for snackbar is not a priority, I have drafted it as a separate issue.  ( #118 )
This PR will be approved/marge after this.

2023-08-10 08:22 UTC, ReiHashimoto approved these changes
LGTM

2023-08-10 08:24 UTC, itutu-tienday approved these changes

2023-08-10 08:25 UTC, merged